### ISSUE TITLE
Custom properties not being generated in proper way, conflicts with Rigify when mmd_tools active

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#101]
Check out https://developer.blender.org/T53842 .

I was having a lot of problems getting Rigify to work well, a lot of bugs-- not making an MMD model, but mmd_tools was loaded, I opened a bug report for Rigify, but according to the Blender devs, it's apparently mmd_tools that is creating properties improperly.

The obvious workaround here is to disable mmd_tools when using Rigify.  But I thought you'd want to know about the issue and read what the devs wrote.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

But I think it is easier to fix this from Rigify, obviously add check code `if prop1 is not None:` can fix it I guess. :) And currently just disable mmd_tools when using Rigify, I'll try to see if there is any solution to fix it from mmd_tools.

**Comment by powroupi** [comment]
This error can be fixed in function `copy_bone` of /2.79/scripts/addons/rigify/utils.py:
```python
def copy_bone(obj, bone_name, assign_name=''):
.
.
.
        # Copy custom properties
        for key in pose_bone_1.keys():
            if key != "_RNA_UI" \
            and key != "rigify_parameters" \
            and key != "rigify_type":
                prop1 = rna_idprop_ui_prop_get(pose_bone_1, key, create=False)
                if prop1 is None: continue # fix this error
                prop2 = rna_idprop_ui_prop_get(pose_bone_2, key, create=True)
                pose_bone_2[key] = pose_bone_1[key]
                for key in prop1.keys():
                    prop2[key] = prop1[key]
.
.
.
```

**Comment by powroupi** [comment]
I think it is more like blender's bug, `pose_bone_1` must has "_RNA_UI" in it, otherwise `rna_idprop_ui_prop_get(pose_bone_1, key, create=False)` will return None. So, here is another solution for fixing this issue ~(it should be better to fix `rna_idprop_ui_prop_get` function)~:

```python
def copy_bone(obj, bone_name, assign_name=''):
.
.
.
        # Copy custom properties
        for key in pose_bone_1.keys():
            if key != "_RNA_UI" \
            and key != "rigify_parameters" \
            and key != "rigify_type":
                prop1 = rna_idprop_ui_prop_get(pose_bone_1, key, create=True) # fix this error
                prop2 = rna_idprop_ui_prop_get(pose_bone_2, key, create=True)
                pose_bone_2[key] = pose_bone_1[key]
                for key in prop1.keys():
                    prop2[key] = prop1[key]
.
.
.
```

**Comment by nathanvasil** [comment]
I don't know.  I don't know enough to understand the exact issue.  From what I understand, yes, I think Rigify should get some code updates in order to become more robust (and you might consider sharing them with Blender devs), but from what I read, I don't think that's going to happen.  In a perfect world, I think both Rigify and MMD Tools would get fixes.  But of course it's not a perfect world; people's time and attention are limited.

It's no longer an issue that affects me personally since I now know the workaround.  If you don't feel like working on it, I can add a section to known issues in the wiki, and maybe somebody else won't bang their head into the wall like I did over the last couple days :)  (Getting close to completing my first wholly original character model!  Thanks MMD and MMD Tools for getting me into Blender!)

**Comment by powroupi** [comment]
I'm sorry, I think mmd_tools won't get fixes about this issue which should be fixed from Rigify or Blender. :cry: 

Because Blender creates "API Defined" custom properties automatically without adding "_RNA_UI", Rigify will potentially get this error no matter which addon defines its custom properties to PoseBone. It is not possible to prevent this error without updating either Rigify or Blender.

And yes, it is better to add known issues in the wiki for now, and thank you so much for your effort to the wiki. :kissing_heart:

**Comment by powroupi** [comment]
I've implemented a workaround for this issue (can't find any better way, sorry), now we can click [Apply] or [Clean] of MMD `Bone Constraints:` before using Rigify's [generate] button to prevent the error.

(change values of [Move+]/[Rotate+] on MMD Bone Tools Panel will apply it, so it can also prevent the error) :smile:

**Comment by 0Curtain0** [comment]
**Blender 2.80**
**MMD Tools v0.7.0** (Jul 12 2019)

```
Traceback (most recent call last):
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/ui.py", line 760, in execute
    generate.generate_rig(context, context.object)
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/generate.py", line 385, in generate_rig
    raise e
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/generate.py", line 361, in generate_rig
    scripts = rig.generate()
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/rigs/spines/super_spine.py", line 948, in generate
    bones['def'] = self.create_deform()     # Gets org bones from self
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/rigs/spines/super_spine.py", line 175, in create_deform
    def_name = copy_bone(self.obj, org_b, def_name)
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/rigify/utils/bones.py", line 203, in copy_bone
    for key in prop1.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

location: <unknown location>:-1
```
I have MMD Tools add-on installed and enabled, but I've never actually used the add-on, except for just importing MMD models into Blender to see how they look. 

Anyway, I was rigging a non-MMD model with the Rigify add-on. 
When I used Rigify's **Generate Rig** button, I got the error. 
I had no idea it was related to the MMD add-on, until I did a google search for the error which lead me to this page. 
Since I don't really use MMD Tools add-on, I really don't know how to take advantage of the workaround. 

> now we can click [Apply] or [Clean] of MMD Bone Constraints: before using Rigify's [generate] button to prevent the error.

Where can I find this?

> (change values of [Move+]/[Rotate+] on MMD Bone Tools Panel will apply it, so it can also prevent the error)

I see this in the Bone tab, but I don't know what to change the values to.

I have a Blender guide for Rigging and Weight Painting, and I want to make sure I inform everyone about this issue: https://www.deviantart.com/xcurtainx/journal/Blender-Guide-Rigging-Weight-Painting-785437846

**Comment by nathanvasil** [comment]
> Since I don't really use MMD Tools add-on, I really don't know how to take advantage of the workaround.

It's easy enough-- especially since, as you say, you don't really use the addon.  In 2.8, go to edit/preferences.  Navigate to the addons tab.  Filter by "mmd".  Click the checkbox to disable MMD Tools addon.  Now you're safe to create your metarig.  If you need to, you can re-enable MMD Tools after generating an armature from your metarig.

**Comment by 0Curtain0** [comment]
Yea, the thing is, I was already in the middle of rigging a character with rigify while MMD Tools was enabled. 
I disabled the add-on after I encountered the error, but the error was still present. 

Since I'm still clueless about powroupi's "workaround", I'm now in the process of restarting the rig from scratch with MMD disabled. 
Not exactly sure how the MMD Tools add-on managed to screw up my work. 
I can't remember interacting with any of the those tools during the project.

**Comment by nathanvasil** [comment]
Oh, I'm sorry, I thought you were talking about the top post work-around.

Considering that the rig isn't actually an MMD model, you might have some trouble.  However, you could try creating a new MMD model (shift a->armature->new mmd model) then joining your armature to the single bone that creates, then using the sidebar ('n' key), mmd tab, to clean+apply.  (If needed, you should be able to separate your bones to a new armature afterwards and unparent from the MMD model empty.)

Untested though.

**Comment by powroupi** [comment]
@0Curtain0, sorry for my late reply, you can just click [Move+] or [Rotate+] on MMD Bone Tools Panel, that's it.

Another way is to type the following 2 lines in Blender Python Console with your armature object selected. [Move+]/[Rotate+] buttons are doing the same trick. :)
```python
>>> from rna_prop_ui import rna_idprop_ui_get
>>> for b in C.object.pose.bones: rna_idprop_ui_get(b, create=True)
```

**Comment by powroupi** [comment]
>Not exactly sure how the MMD Tools add-on managed to screw up my work.

It's because Blender creates API defined properties automatically without creating '_RNA_UI', in this case, `mmd_bone` will be created to the context bone when drawing MMD Bone Tools panel, which will cause the error when using Rigify's **Generate Rig** button. :cry:
