### ISSUE TITLE
clean model

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#113]
Who is it that programmed the "clean model" feature? Did you program this, @powroupi ? This is an excellent feature and an excellent service to the MMD community. I praise very highly this feature of mmd-tools. 

 I am thinking that later we may be able to program something to fix ALL of the model errors which can be fixed in an automated way. In the meantime, it will be very helpful to have a test pmx model which has every error which can be detected by the PMX error checker. If anyone has a PMX model which has an unusually large number of errors, it may be helpful for us to have a copy of this model, if you would be kind enough to upload it for us. And if anyone has any ideas about how to intentionally create errors in a PMX model, this could be helpful also.

**Comment by Hogarth-MMD** [comment]
2 tutorials about fixing PMX model errors:

PMX Validation: Every modeler should know and do
https://permayuyuko.deviantart.com/journal/PMX-Validation-Every-modeler-should-know-and-do-469367980

PMD info guide to fixing models [tutorial]
https://likeabaka.deviantart.com/journal/PMD-info-guide-to-fixing-models-tutorial-615658649

**Comment by Hogarth-MMD** [comment]
Okay, Here is my listing of PMX errors, analyzed neatly into categories, with better translations than someone can get from Google Translate.
Any ideas related to automatically fixing these errors? (There is no guarantee that my understanding of these errors is complete or perfect yet.)


No name is assigned to:
model, material, bone, morph, rigid body, joint

Duplicate names of:
materials, bones, morphs, rigid bodies, joints

no model comment


references to something which does not exist:

- the vertex index of a face's vertex does not exist in the model
- texture name, toon texture name, sphere texture name (referring to an image file which does not exist)
- name of parent bone refers to a bone which does not exist
- the name of child bone refers to a bone which does not exist
- the name of a constraining bone ("grant parent", copy rotation or copy movement target bone) refers to a bone which does not exist
- the name of the IK target bone, or of an IK linked bone, refers to a bone which does not exist
- the name of a rigid body's bone refers to a bone which does not exist
- one or both of the names of a joint's rigid bodies refer to a rigid body which does not exist


Morph offset reference invalid: 0 | ... ○ OK
Here are my guesses about what this error message may mean:
Vertex index in a vertex morph or UV morph is out of range. The vertex index is higher than any index of a vertex in the model
OR 
the material index of a material in a material morph does not exist
OR
a morph name in a group morph refers to a morph which does not exist


Display Panel Errors:

Display Panel Group with no name
Duplicate names of Display Panel Groups
Bones not assigned to a Display Panel Group
Morphs not assigned to a Display Panel Groups
Duplicate names of bones in Display Panel Groups
Duplicate names of morphs in Display Panel Groups
Display panel bone name refers to a bone which does not exist
Display panel morph name refers to a morph which does not exist
Zero display panel groups
Root and/or Expressions (System) Display Panel Groups do not exist


Other errors:

More than 4 additional UVs

5 Vertex errors:
invalid vertex normals
invalid vertex weights
2 SDEF errors of vertices
vertices which have no face

2 Surface/Faces errors (in addition to 1 Surface/Faces error already mentioned above)
invalid faces (faces which are not triangles)
duplicate faces

3 Materials errors (in addition to 5 Materials errors already mentioned above):
material which has no faces
sphere texture is named but it is disabled
faces which have no material or more than 1 material (counting faces with materials)

4 Bones errors (in addition to 7 Bones errors already mentioned above:
too many bones
circular causation/infinite loop error of bones
bone hierarchy order check failed
incorrect order of bones (parent bone should be listed before child bone)

**Comment by nathanvasil** [comment]
Are you asking how they should be dealt with?  Ideally?

> the vertex index of a face's vertex does not exist in the model

Broken face, delete the face, schedule rerun of PMXE validation in case you orphaned any vertices

> texture name, toon texture name, sphere texture name (referring to an image file which does not exist)

Ignore error so user can mess with files later.

> name of parent bone refers to a bone which does not exist

Parent bone to -1 (world)

> the name of child bone refers to a bone which does not exist

Replace with arbitrarily chosen offset (like 0, 0, -1).  Doesn't matter.

> the name of a constraining bone ("grant parent", copy rotation or copy movement target bone) refers to a bone which does not exist

Disable the copy rotation/movement.  Can break models.  Always happens to newbies that ruin their both-eyes bone.

> the name of the IK target bone, or of an IK linked bone, refers to a bone which does not exist

If highest number bone in IK chain has a single child bone without a higher deform tier than the IK bone, make that the target.  Otherwise disable IK on the bone.

>the name of a rigid body's bone refers to a bone which does not exist

Delete the rigid body if it's not referenced by any joints.  It will fall through the world and eventually crash MMD.  Otherwise ignore the error, it's not a problem.

> one or both of the names of a joint's rigid bodies refer to a rigid body which does not exist

Delete the joint.  It will crash MMD on load.

> Display Panel Group with no name

Create arbitrary names (new, new001, new002...)

> Duplicate names of Display Panel Groups

Rename arbitrarily.

> Bones not assigned to a Display Panel Group

Make unassigned bones hidden.

> Morphs not assigned to a Display Panel Groups

Ignore, sometimes desirable.

>Duplicate names of bones in Display Panel Groups
> Duplicate names of morphs in Display Panel Groups

Rename arbitrarily.


>Display panel bone name refers to a bone which does not exist
> Display panel morph name refers to a morph which does not exist

Delete display panel entries for non-existent bones/morphs.

> Zero display panel groups

Create a new display panel group and put the root bone in it.

> More than 4 additional UVs

Delete the UV maps, you can't do anything with them.

> invalid vertex normals

Recalculate from face normals.

> invalid vertex weights

Convert single weighted verts to BDEF1, convert doubled weighted BDEF4 to BDEF2, normalize weight values.

> SDEF errors of vertices

Recalculate centers.  If you can't do that, convert to BDEF2.

> vertices which have no face

Delete the vertices.

> invalid faces (faces which are not triangles)

Shouldn't happen, but you could run a Blender triangulate function on them.

> duplicate faces

Delete the face with the highest index.

> material which has no faces

Delete the material.

> sphere texture is named but it is disabled

Ignore, not an issue.

> faces which have no material or more than 1 material (counting faces with materials)

Assign the first to mat 0, drop highest indexed materials for the latter.

> too many bones

Didn't even know that was possible, lol.  Unlikely to happen.  Best bones to delete are those with the highest deformation tier (most important) and highest index (second most important).  Re-run validation if you delete bones, you may need to do things with weights.

> circular causation/infinite loop error of bones

Drop any appends parented to the last bone in the list (highest deform tier->last in list).

> bone hierarchy order check failed

Not sure what that means.

> incorrect order of bones (parent bone should be listed before child bone)

Increase deform tier of child by 1.  Do this recursively because the child's children will need it to happen too.

**Comment by Hogarth-MMD** [comment]
Thanks for your thoughts, @nathanvasil, some helpful ideas there. A missing piece of information for me is which errors can already be automatically fixed by mmd_tools or by Blender. Can @powroupi help with that information? Or is he maybe too busy?  

Blender automatically corrects bone order. I think Blender does some automatic renaming of duplicate names (but not of display panel items if they are not in the same display panel group, and not of duplicate physics names).

**Comment by Hogarth-MMD** [comment]
"bone hierarchy order check failed
Not sure what that means."

I am clueless about what this means, unfortunately. :-(

**Comment by Hogarth-MMD** [comment]
vertices which have no face
Delete the vertices.

Blender has a Select Loose Geomety operator to select these vertices before deleting them.

**Comment by Hogarth-MMD** [comment]
invalid faces (faces which are not triangles)

According to the tutorial information, this refers to faces which have the same vertex listed twice in the same face, making the face an edge.

**Comment by Hogarth-MMD** [comment]
"bone hierarchy order check failed
Not sure what that means."

Quoting from the tutorial by Permayuyko:

" Transformation assignation hierarchy order validation/improper transformation assignation parent:
This check is about the bone transformation assignation just below the display target, which is used to make one bone move/rotate by itself as the other does the same.
(All eye bones uses this. Also, a workaround for post-IK bones before MMD v8.12 uses this too.)
Again, if you happen to have the child-parent relationship not following the bone order, or assigned a target that's invalid (for many reasons), PMXEditor'll report errors. "

**Comment by nathanvasil** [comment]
> invalid faces (faces which are not triangles)

Then just delete the face, then recheck for newly orphaned verts.

> bone hierarchy order check failed

Okay then it's the same issue as something else.  Drop any appends parented to the last bone in the list (highest deform tier->last in list).

> More than 4 additional UVs

alternative to my earlier suggestion: export as a UV morph to preserve the data, if in a not-useful form.

> which errors can already be automatically fixed by mmd_tools or by Blender

Depends on how you're doing things.  If you're making a new model in Blender for exporting to mmd, most of those errors should be impossible.  Only exceptions, I think, are the display panel ones, and it's not really a big issue.  (Display panel stuff can crash MMD eventually, but not from blender->mmd use, more from crazy beginners importing a million models into one file.)  You could probably get SDEF errors, but only by trying really hard.  Not sure about physics, but I think it's unlikely that people are using Blender to do physics for MMD models without a good prior understanding of MMD physics.

If you're importing a .pmx and then exporting it, more of those issues can persist.  All the bone ones will persist if you keep the bone order modifier.  I believe mmd tools preserves orphaned verts but not degenerate (2-sided) faces.  Physics issues will remain from the original model.  Unfortunately, mmd_tools isn't importing bones perfectly to begin with; I think it would be preferable that mmd_tools not break a model being imported for mesh edits, than that it tried to fix something that it didn't know how to import correctly in the first place.  Physics issues might be worth fixing, but this is also where the best fixes are among the poorest, because orphaned joints and rigids probably refer to something, and it would often be nicer to preserve that something's details even if it ends up crashing MMD.

> not of duplicate physics names

Duplicate body/joint names gives a validation warning, but it has zero impact on MMD use or editing.  You could give them .001 etc but you don't really have to.

The actual errors that are going to matter are stray vertices (beginners end up with a billiion which impacts editing performance), incomplete joints (crashes mmd), duplicate display panel entries (crashes mmd when you have enough), bone order from broken imported models, invalid copy rot/move parents (will screw up deformation and people won't know why), duplicate morph names (can error, eventually crash mmd).

There's one other thing I didn't see in your list that's important.  Unnormalized or non-orthogonal local axes are very bad.  mmd_tools almost certainly handles this correctly already.

**Comment by powroupi** [comment]
Sorry for the late reply. I'm not fully understand those errors, but I may be able to fix some if you provide me some sample pmx/pmd files to reproduce the errors. Maybe other developers could fix some as well. :blush:

**Comment by Hogarth-MMD** [comment]
https://sta.sh/0bxalm275xv

Evil test cube of infinite errors 1.0 (It does not have all errors yet.)

When I imported this cube into Blender, it gave me this error message:

"This model is complete garbage and it is not my job to import this complete garbage model into Blender. signed powroupi "

Just joking. :smile:  Surprisingly the import of this model into Blender was successful, but after exporting it from Blender, some errors remained. Surprisingly no correction of duplicate bone names happened.

**Comment by Hogarth-MMD** [comment]
A new mmd_tools wiki tutorial by me. Suggestions for improving it are welcome.

PMX error checker quick reference
https://github.com/powroupi/blender_mmd_tools/wiki/PMX-error-checker-quick-reference

**Comment by Hogarth-MMD** [comment]
Making a test model which has all errors is not so easy. I eventually reached the stage of frustration with this effort. I thought that I could create errors on an MMD model in Blender, but Blender and/or mmd_tools automatically fixes some errors, so the test model will end up having fewer errors, instead of more errors. :disappointed:

**Comment by 3dcinetv** [comment]
Sometimes I get a pxm all over broken places, all their edges and vertices, though very near distance, (aka 0.001) when I try to : "merge by distance": 0.0001 edges or vertices do not merge in Blender 3.6, I don't know if this is a blender issue or a model issue. Does "FIX MODEL" help with this? (merges closest vertices together)?
