### ISSUE TITLE
number of IK iterations?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#116]
In mmd_tools, the number of iterations/loops that are listed in a .pmd or .pmx model is exactly the same as the number of iterations of the IK constraint in Blender.
In pymeshio, the number of iterations in Blender is 10 times the number of iterations in PMD editor or PMX editor.  So, who is right about this? ousttrue or sugiany? I have no idea which of these guys has programmed it correctly.

**Comment by nathanvasil** [comment]
> I have no idea which of these guys has programmed it correctly.

In that specific sense, probably neither.  Blender uses a different IK algorithm than MMD.  I don't know of any place that documents MMD's implementation (although it must be available somehow, because MMM and PMXE both match it completely.)  With different implementations, there's not really any way to compare iteration counts.  All you can say is whether the iterations are sufficient to avoid unpleasant angles.
