### ISSUE TITLE
Imported file reliably crashes Blender

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#13]
This (pornographic) file at http://www.mediafire.com/download/em1lwobzhdhba5h/cockandface.pmx reliably crashes Blender 2.77 immediately after import.  To recreate, import the file, 'a' to deselect, rmb to reselect, hit tab to enter edit mode.  Also crashes on 'a' to deselect, rmb reselect, separate by materials.  Does not crash using unforked MMD_Tools.

**Comment by powroupi** [comment]
Thank you for reporting this issue. I confirmed it. :)
It is because the model contains some invalid faces that cause problems in calculating custom normals.

I can solve it in two ways:
- 1. Import the file, rmb select the mesh object, open blender python console window, type command: `>>> bpy.context.object.data.validate()`, hit tab to enter edit mode in 3d view window, no crash!!!
- 2. Comment out the line [import costom normal](https://github.com/powroupi/blender_mmd_tools/tree/7d7a7a974a0d20812f7d7915a9f14b3659245d14/mmd_tools/core/pmx/importer.py#L627), start blender, import the file, rmb select the mesh object, hit tab to enter edit mode in 3d view window, no crash!!!

But both will lose some data:
- 1. lose some invalid faces, maybe some others (not sure what blender did).
- 2. lose custom normals.

It is recommended to validate your model in PMXE before importing into blender. You can reference [Here](http://permayuyuko.deviantart.com/journal/PMX-Validation-Every-modeler-should-know-and-do-469367980). It might not have the issue if you model it in blender at begining.

So, i may not fix it for now. :sunglasses:

**Comment by roycramer** [comment]
Also had this issue, your first solution worked best, it would be nice if there were a button to do it but I'm just happy my model works again!

**Comment by powroupi** [comment]
Okay, i think this issue is solved now. :smile: 

Now, you can check option `Clean Model` on importing, the importer will remove invalid faces and unused vertices, giving you a more clean model. If you are sure your model is valid and clean, you can uncheck that option to slightly improve the performance on importing. :)

Have fun! :smile:

**Comment by nathanvasil** [comment]
Confirmed.  Looks fantastic, thank you.  Appreciate you putting the time into issues like this, I would love it if MMD could be an introduction to Blender for more people-- people who don't always have the wherewithal to push through errors like this.

I can't comment on closed issues, even though I'm still finding interesting information regarding them.  I'll share them here.

Found more information regarding my vertex/normal corruption problems.  They are not due to your bones (confirmed with a boneless dummy), but to Blender's handling of remove doubles.  Removing doubles in PMXE doesn't create the same problem-- even importing a PMXE-pruned model into Blender, redundantly removing doubles, and recomputing normals, I end up with proper normals, whereas doing it in Blender, I'd end up with a bad model.  I found this very interesting, even though it's not directly relevant to MMD_Tools.

Finally, I found a corner case where vertex order matters.  Shaders can reference the actual vertex number.  For instance, a particle effect might use _INDEX mod 4 in order to keep track of exactly which plane of potentially thousands of particles it's currently dealing with.  This is a corner case, and unlikely to be broken by MMD tools, just thought you might find that interesting.  (Crazier effects, however, could rely on a vertex order that an import/export cycle would break.)

edit: oops, _INDEX mod 4 could be used, but you'd more typically be using floor(_INDEX/4) .

**Comment by powroupi** [comment]
You're welcome. I'm interested in solving issues, and i'll learn something when looking for the solutions. :smile: 

> I can't comment on closed issues,...

I can see "Comment" button when i explore the closed issues of other people's repository (but i didn't hit the button), so you might be able to make comments, and you should be able to reopen and comment your old issues if you want. And I prefer people to open issues so that it will be visible to everyone. :)

> Found more information regarding my vertex/normal corruption problems....

Currently, the vertex will be split on exporting if it has different normals (on hard edge) or different uv locations (uv seam...). And in blender, it is safe to remove doubles **only if** the vertices has the same data (shape key offset, uv, ...), you need to carefully select those vertices which are safe to remove doubles because blender won't check that for you. And it's never safe if the model has uv morph data, you probably need to recreate them after removing doubles.  :expressionless:

> Finally, I found a corner case where vertex order matters....

I don't know much about MMD shaders. I think it's possible to keep vertex order of imported model, but editing the model in blender could change the order which is controlled by blender, ...maybe we could add a vertex group to control vertex order on exporting, but i don't think it's easy to use (in general, we wouldn't care about vertex order).  :pensive:

**Comment by nathanvasil** [comment]
Oh.  I guess I can comment.  I don't know from where I got the idea I couldn't.

Vertex order is almost not a real issue, because it's so unlikely to ever matter, and because I bet you're already doing it the best way.  With a simple particle system like I was describing, there's no need to go to Blender in the first place.  All you want is a bunch of UV mapped planes that you can make anywhere.

There are situations where it might be cool to take advantage of vertex order in complicated ways.  For instance, you could make a burn/smolder effect that progressed along vertex order, to make it appear that something was burning upwards.  In a case like that, you'd want to take advantage of the ability of something like Blender to re-order vertices.  PMXE has no such capability, not that I know of.  With any significant mesh edit, you'd need to renumber your vertices anyways.

So if this small issue is actually one you're interested in, I would think that preserving imported vertex order would be far less important than preserving Blender's vertex order.  I'm not sure, but I expect that's how MMD Tools is already handling it.  Which is why it's just an interesting thing I learned that isn't even deserving of an issue, but just one that I thought you might find interesting too :)

Looks like the doubles is related to custom split normals data.  Weird situation though, my normals wouldn't appear to change with vertex/face normals on, but the mesh was obviously different.  I guess Blender was trying to protect me from too much information :)

**Comment by powroupi** [comment]
I think i can update my branch next week with the vertex order controlling feature. Maybe we can add a vertex group (say "vertex_order") to define custom order or just use blender's internal vertex order if the vertex group ("vertex_order") is not provided. And an option for that on exporting to determine whether use that feature or not. :sunglasses: 

> Looks like the doubles is related to custom split normals data...

There are 3 types of normals in blender: **Vertex normal / Vertex-per-face normal / Face normal**. You can toggle visibility in "Mesh Display" panel from Edit Mode. **Vertex normal / Face normal** are controlled (calculated automatically) by blender. The custom normals are **Vertex-per-face normal**, but we need to search addons to edit custom normals individually, blender does not provide a handy tool to modify custom normals individually at the moment (only **"Normal Edit"** modifiers). So it might be the reason... :)

P.s.
Enable "Auto Smooth" (Properties window -> Object data tab -> Normals panel -> Auto Smooth) to view the result of **Vertex-per-face normal**, disable it to view the result of Vertex/Face normals (calculated by blender).

**Comment by Hogarth-MMD** [comment]
You should always run error checking on your model in PMD editor and correct all model errors before trying to import your model into Blender. Tutorial about that here:

PMX Validation: Every modeler should know and do
http://permayuyuko.deviantart.com/journal/PMX-Validation-Every-modeler-should-know-and-do-469367980

**Comment by powroupi** [comment]
Well, now we should be able to control the vertex order through vertex weight of vertex group named "mmd_vertex_order" on exporting, the larger weight means the larger vertex index, and the vertices those are not in the group will be the last. :smile:

Note:
- If vertex group "mmd_vertex_order" is not provided or method "Blender" is choosen, the blender's vertex index of the mesh will be used on exporting.
- In multiple meshes case, the mesh (object) order is relevant as well.
