### ISSUE TITLE
Issue with MMD Shading

### ISSUE THREAD

**Issue by ghost** [powroupi/blender_mmd_tools#137]
I'm not sure if I just installed this wrong, or if this is an actual issue. When using the right side panel of the viewport, there is only one section relating to mmd, the mmd shading menu. The mmd display menu that I've seen others use is not there, and when I try any options in the shading menu, I get and error.

RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\operators\view.py", line 75, in execute bpy.context.scene.display_settings.display_device = 'sRGB'
TypeError: bpy_struct: item.attr = val: enum "sRGB" not found in ('None', 'sRGB / BT.709')

location: C:\Games\Steam\steamapps\common\Blender\2.79\scripts\modules\bpy\ops.py: 189

If I move it to the Steam part of blender, then I get this when tying to select an mmd shader:

'Object' object has no attribute 'is_mmd_glsl_light'

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

>TypeError: bpy_struct: item.attr = val: enum "sRGB" not found in ('None', 'sRGB / BT.709')

I can bypass this error by adding a try-catch statement. (not sure why you have "sRGB / BT.709" instead of "sRGB") :)

>'Object' object has no attribute 'is_mmd_glsl_light'

This should not happen if `mmd_tools` is installed correctly. :confused:  Please try re-enabling (or re-installing) `mmd_tools` again, and check out [system console](https://docs.blender.org/manual/en/dev/advanced/command_line/introduction.html#microsoft-windows) messages, let me know if there is any error messages. Thank you. :)

**Comment by ghost** [comment]
Yeah, the second part was me testing if I had done something wrong. I didnmt expect it to be right, but I wasn’t sure. Thanks for clarifying it!

**Comment by powroupi** [comment]
Okay, you can close this issue if you don't find any further issues in the latest `mmd_tools`. Thank you. :smile:

**Comment by ghost** [comment]
Will do, I’ll be able to check tomorrow. I’ll reopen the issue if I find anything else, thanks!
