### ISSUE TITLE
mmd_tool stop working on blender 2.80(Jun 29 2018)

### ISSUE THREAD

**Issue by niqiuz** [powroupi/blender_mmd_tools#157]
![screenshot](https://user-images.githubusercontent.com/40124700/42131675-c26bdbe6-7d39-11e8-90fd-6f408eddf868.PNG)

Working very well on the 2.79.
I am using win7, do I need to change to win10?

**Comment by Darkblader24** [comment]
Of course it's not working yet. Blender 2.8 is still in early development, there are a lot of bugs and a lot has changed and will change as well. And @powroupi is aware of this. 
You should use Blender 2.79 until 2.8 is officially released and mmd_tools supports it.

**Comment by niqiuz** [comment]
@Darkblader24 Thank you for replying, I want to try eevee, so I packaged a .blend at 2.79 and opened it at 2.80. This also works.

**Comment by Takuyax** [comment]
The official date for the final python API is September 19: https://code.blender.org/2018/06/beyond-the-code-quest/
So that's the date when it makes sense to start work on porting the add-on to 2.8. Porting earlier than that might mean wasted time.

@niqiuz You can also later import motions in 2.79 and append them to your 2.8 project file, since the data remains compatible.
