### ISSUE TITLE
Bone MMD properties changing mysteriously under mirror

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#165]
This is a poor bug report, because I can't yet create a controlled, reproducible test case, but it's something I've been noticing and where I've heard of issues that sound related.  I thought I would bring it up just in case.

MMD bone properties seem to change when an MMD armature is edited with X Mirror enabled in armature options.  In particular, Japanese bone names can change.  This seems to only happen under some circumstances, I don't know which.

The related issue that I heard of was somebody who was making bone morphs and found armatures changing when mirroring poses for use in bone morphs created in Blender.  It sounds very similar.

I don't know if this is any use, sorry that I can't be more specific.  If I manage to create a good way to reproduce it, I'll provide the file.  If I can't, I guess I'll just leave this open for a bit, but of course you can feel free to close it any time, it's just intended to be a helpful heads up; I realize that there is probably not enough information to deal with the issue, or to even verify that it is an issue and not just me hallucinating or something.

**Comment by ptrthomas** [comment]
@nathanvasil maybe this helps, maybe it won't but I struggled to mirror MMD motions in blender until I figured out that the bone-roll was not symmetrical and caused issues. so my workflow is like this now:

- import MMD model
- select all armature bones in edit mode, clear bone roll
- with all the bones still selected, Armature->Symmetrize

**Comment by powroupi** [comment]
Sorry, I can't reproduce this issue with X Mirror enabled. :cry: 

The related issue is #20 (paste flipped pose) in Pose Mode, which could break Bone MMD properties.

Another unreported issue is Duplicate Bone in Edit Mode, which could break Bone reference of MMD Bone Morph and Rotate/Move Append. The MMD Bone ID is assigned when creating Bone Morph or configuring Rotate/Move Append. If you duplicate a bone, the MMD properties (`mmd_bone`) will be duplicated as well, `mmd_tools` will be confused by the bones which have the same MMD Bone ID (if ID >= 0) so that bone morph and Rotate/Move Append could get weird export. In this case, you have to reset a bone's MMD properties by removing `mmd_bone` in `Custom Properties` panel of Pose Bone to make sure the Bone references are correct. (the same problem, Duplicate Material could break Material Morph) :sob:

**Comment by nathanvasil** [comment]
Oh, I'm sorry, #20 would be a better place for any comments related to this, although it sounds like a difficult problem.  If I can provide any good test cases, I'll post them there.  Thanks.

**Comment by nagadomi** [comment]
One problem I noticed is that when using Delete->Undo in (Armature)Edit Mode,  `mmd_bone` property may not be Undo.

1. Select the armature
2. Edit Mode
3. Select `arm_R` bone
4. Delete `arm_R` bone (X)
5. Undo (Ctrl Z)
6. `arm_R` will be reverted but `mmd_bone` property is empty.

This is probably because PoseBone is recreated.
