### ISSUE TITLE
Blender multi-threading

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#166]
In the Blender 2.77 release notes was this dramatic announcement:

"Better threading handling: Blender is now massively multi-threaded."

After that I experienced a dramatic increase of speed, the same blistering fast speed that I can get in MMD. Based on that experience, I deduced that MMD's blistering fast speed probably comes from multi-threading.

In a later version of Blender, maybe 2.79, I remember that it was announced that Blender multi-threading was defective and had been removed from Blender. Since then I have been limping along with the same old Blender slow speed.

The Blender release notes are here:
https://en.blender.org/index.php/Dev:Ref/Release_Notes

I just looked at these release notes and I could not find the announcement of multi-threading being removed from Blender.
Does anyone know what the situation is with multi-threading in Blender? I miss that increase of speed.

**Comment by nathanvasil** [comment]
Some things are, some things aren't.  Cycles rendering is pretty close to perfectly multi-threaded.  Physics isn't multi-threaded at all (may be due to the nature of the problem, I don't know.)

If you're curious about how multi-threaded a particular task is, and you have a multi-core processor, just open your task manager and look at the cpu usage while you do something demanding.  At 100%?  Well multi-threaded.  Stuck at 25% on a 4-core?  Not multi-threaded.  There are occasions when that's not true, like when your CPU is sitting around waiting for your GPU to finish some huge task it's been given.

MMD isn't fast because of multi-threading, it's because it uses a different kind of rendering, the kind of that game engines use.  That means that there are some things it can't do (like reflections of reflections, like arbitrary layers of transparent materials in fog, like per-pixel refraction.).  It's not optimized to do everything, it's optimized to do things at close to real-time.

**Comment by Hogarth-MMD** [comment]
This is interesting information about using the Windows task manager to detect multi-threading or lack of multi-threading. Thank you for sending this information to me. Previously I did not know this.

I am the author of a tutorial about the Beamman water effect. The Beamman water effect has both reflection and refraction. With the Beamman water effect loaded into MMD, I can still get the blistering fast preview and final rendering speeds of MMD.

**Comment by nathanvasil** [comment]
Beamman's water (v5.6) does not do per-pixel refraction.  It does a parallax-like effect, using the plane of the water and the depth of the water.  It combines this with some specular effects.  But it uses only a single vector, the normal of the water plane, to "bend' the light, regardless of the shape of the object bending said light, regardless of the direction with which light strikes the surface.  It's a hack to give the impression of refraction.  You can contrast this with Blender's refraction, which works under different principles: since Blender is raytracing: for every pixel, it sends a different vector, each of which can be bent in a different direction.

Beamman's water effect does include a mirror, but what I said was not that reflections are impossible in MMD, but that reflections of reflections are.  Beamman's water does not provide reflections of reflections; no matter how many copies you load, you'll find it impossible to see into infinity.  Now, technically speaking, it isn't quite true that reflections of reflections are impossible in MMD; you could render the scene once for the main scene, once for the reflection, once for the reflection of the reflection, once for the reflection of the reflection of the reflection....  Do that 12^number of mirrors times and it might as well be perfect, you won't see the imperfections until you go past 4k resolution.  But this is slow and cumbersome, and MMD effects do not bother doing this.  If they did, they would rapidly reach the point where they stopped being faster than Blender.  The same goes for per-pixel refraction.  If you wanted, you could render the scene once for every single pixel times every single refracting surface and achieve per-pixel refraction in MMD, but in doing so, you would stop being faster than Blender.

**Comment by Hogarth-MMD** [comment]
MMD CPU usage 25%. Open Blender and set up an animation. CPU usage 25%.  If I play back an animation in MMD, the CPU usage stays at 25%. If play an animation (with physics) in Blender, CPU usage jumps from 25% to 33%. Stop playing animation in Blender, CPU drops back to 25%. Shut down Blender, CPU usage 25%. Shut down MMD (both programs closed), CPU usage drops to about 1%. 
I don't really understand it. Why is MMD so fast? No sign of any "massive multi-threading" with either program.

**Comment by nagadomi** [comment]
HLSL (MME) is performed on GPU. It is parallelized for GPU cores, so it is not related to (OS-level)multithreading for multicore CPU.
I guess MMD's all screen drawing process is performed in DirectX(GPU), contains vertex transformations. In blender, it is probably performed on CPU because there are complicated processes such as modifier stack. GPU is used only for rendering. So it's slower than MMD.

If you want to play animation in realtime on blender,
1. Bake physics simulations (Scene Tab > Rigid Body Cache > Bake/Bake All Dynamics)
2. Change `Sync Mode` (Timeline window) to `AV-sync`

**Comment by nathanvasil** [comment]
1) If you have models loaded in MMD, you are playing an animation even if you haven't hit the play button.  If you want to use your task manager to check on multicore use, close all applications but the one you're testing and use a task that can't be done in real time-- ie, in MMD, use enough high vert models and physics that you can't play it at 30 fps.  Know that this is only a rough way to gauge use.  If you have a 3D accelerator, the bulk of your rendering time is from calculations made on your GPU, not calculations made on your CPU.  You can minimize part of the GPU component by minimizing your resolution, which only costs fill-rate, something your CPU isn't involved in at all.

2) When you talk about playback in Blender, what exactly do you mean?  Do you mean rendering a video?  Do you mean previewing an animation in solid mode, textured mode, GLSL mode?  If Blender worked right, a GLSL preview would run about as quickly as MMD, because they're both basically rendering in the same (game-engine) fashion.  However, it would not at all surprise me if MMD ran faster in this case, simply because Blender isn't made for real-time rendering and MMD is.  That drives where developers spend their effort.

Of course, you'd need an apples-to-apples comparison: equal vert counts, no subsurf, no extra physics steps, no add-ons or drivers running Python in the background, stuff like that.

**Comment by Hogarth-MMD** [comment]
My Windows 10 task manager gives the number processes, threads and handles. I don't see any massive increase of threads, though, which is destroying my multi-threaded theory. 

Previously I was having a problem in Blender of 15 FPS preview playback of a 30 FPS animation. But that problem seems to have mysteriously fixed itself. MMD and Blender both use a lot of CPU and RAM. If I load a large number of models and animations into MMD, I can increase the CPU usage to 50% or more. Windows task manager tells me nothing about GPU usage.

@nathanvasil and @nagadomi , you guys are great! Thanks so much for your help. And congratulations again to @nagadomi for the clever new SDEF feature. Doing the benchmark testing made me interested in the subject of increasing speed.

**Comment by Hogarth-MMD** [comment]
" Cycles rendering is pretty close to perfectly multi-threaded." Sorry if I'm a bit stupid about this subject, but how do I see that? Render with cycles and my CPU usage jumps to 100% ?

**Comment by Hogarth-MMD** [comment]
In Windows, is there nothing that allows me to see the GPU usage?

**Comment by Hogarth-MMD** [comment]
OMG, that is exactly what happens. I tried to render with Cycles and the CPU usage jumped to 100%! So this is multi-threading.

**Comment by Hogarth-MMD** [comment]
In the past I have never used Cycles because of slow speed. I just tried to render with Cycles for the first time in a long time, but all the rendering is greyscale. How do I fix that? I did click on the mmd_tools Convert materials for Cycles button.

**Comment by Hogarth-MMD** [comment]
Okay, mesh object must be the active object to convert materials to Cycles.
