### ISSUE TITLE
scaling bones of a PMX model ?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#173]
Is there any way to achieve the equivalent of scaling a bone of a PMX model outside of Blender? 
In Blender, a bone can be scaled in x and/or y and/or z directions and the vertex group of that bone will be scaled in x and/or y and/or z directions.

**Comment by nathanvasil** [comment]
You can do bone scaling in PMX, using the transformation window (f9).  This scaling uses global axes, but for most bones of most MMD models, reasonable local axes align with global axes; where they don't, the model can be posed before scaling.  PMXE allows separate scaling by X, Y or Z axes, as well as options to propagate scale through child bones.  For best results, physics should be disabled, and attached rigid bodies won't be scaled (because MMD's rigid body primitives don't really support non-uniform scaling).  You can save a model modified via the transformation window as a new model.

Doing it in Blender is probably better for most purposes though.  More control, easier to do.

MMD itself doesn't support any kind of dynamic, animatable bone scaling.  Which is too bad, there are some cool things you could do with it.
