### ISSUE TITLE
gridfill mysterious issue

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#175]
Miku gridfill
https://sta.sh/0265gtch3erc

![miku gridfill](https://user-images.githubusercontent.com/10057979/45950068-36e4d480-bfcc-11e8-8d28-cede86f0daf0.jpg)

**Comment by Hogarth-MMD** [comment]
I was experimenting with the Blender gridfill operator as a modelling tool. Select a rectangle area of a model. Delete the rectangle area. Use the gridfill operator to fill that deleted area. When the model is exported to MMD or MMM and a VMD dancing motion is applied to the model, the gridfill area will jump back and forth about a meter if front of, or to the side of the model, or down to the floor. This problem does not happen if you animate the model in Blender. I tried everything that I could think of to fix this problem, but it is mysterious and I don't know how to solve it.

**Comment by Hogarth-MMD** [comment]
I tried running the PMX error checker and correcting model errors. The PMX error checker does not detect this problem. I tried turning off physics calculation. This is not a physics issue. I tried moving and rotating bones. I tried exporting the model with the 3 different vertex order options. Nothing helped. I don't know what else I can try.

**Comment by nagadomi** [comment]
It seems to be a shapekey problem.
If you change a shapekey value(e.g. 真面目), you can also reproduce the problem on blender.

**Comment by Hogarth-MMD** [comment]
Thanks @nagadomi , it looks like you have solved the puzzle. :+1:  Blender's gridfill tool (Blender 2.79b) is apparently an extreme buggy piece of garbage. It messes up every shape key of a model. This is a Blender gridfill issue, not an mmd_tools issue.

**Comment by Hogarth-MMD** [comment]
If one of the shape keys (not the Basis shape key) is active when I use gridfill, then this problem is avoided. But if the Basis shape key is active when I use gridfill, then every shape key is messed up.

**Comment by Hogarth-MMD** [comment]
This problem seems to happen with ALL deletions of vertices.  If the Basis shape key is active when you delete vertices, all of the shape keys are messed up. It's a weird time-wasting Blender bug.

**Comment by nathanvasil** [comment]
There are times that it doesn't occur.  But yes, in general, it's a bad idea to add or remove vertices from a mesh with shapekeys in Blender.  And yes, there are some pretty obvious improvements that could be made on that front.  Issues with shapekeys and PMX models aren't MMD Tools fault, they're Blender's fault.

In this case, the part of the mesh with which you're interested in working doesn't look like it would have any important information from shapekeys.  What I would probably do is temporarily separate it to a different object in order to work with it.  Once separated, all shapekeys on the separated objects can be deleted (via the down arrow shapekey menu).  Then, when you're done working with it, you could choose to rejoin it to its original object.  Since it has no shapekeys at that point, it will use its basis (only) for its vertex position for all shapekeys.

There is also the "blend from shape" option in the specials menu that will allow you reset the positions of selected vertices in a shapekey relatively painlessly (assuming you don't have a ton of shapekeys that all need editing.)  On the operator panel, disable Add, select Basis as the blend shape, and set the influence to 1, and you'll reset the positions of your selected vertices to their Basis position.

If you need to preserve shapekeys through vertex editing, the best way to do so, in my opinion, is to copy the original mesh and use it as the target of a surface deform modifier.  This will drag newly created vertices along with the shapekeys of the original mesh.  Then, you can write the surface deform as a new shapekey.

**Comment by Hogarth-MMD** [comment]
Thanks @nathanvasil , I had no idea how to correct this problem after the damage has already been done. I did a Google search for "Blender blend from shape" and I found this stackexchange information, which mentions several techniques:

Revert vertex position to Basis Shape Key
https://blender.stackexchange.com/questions/2941/revert-vertex-position-to-basis-shape-key

I have been simply been making sure that the "Basis" shape key is not the active shape key  when I delete vertices. I haven't noticed any problem with that technique.

**Comment by Hogarth-MMD** [comment]
I think that destructive model editing really is an mmd_tools issue, because users of mmd_tools might like to have some tutorial information about the subject of destructive model editing. Remove Doubles is an operator that I frequently use to get rid of unsightly seams. mmd_tools has 3 export options for vertex order. That is also related to the issue of destructive editing. @powroupi mentioned that SDEF data will be unreliable after adding or deleting vertices. Quoting from the previous discussion about this subject:

If someone edits a model to add or delete vertices, will any of the model's data be messed up as a result of adding or deleting vertices?
UV morph data?
Vertex morphs data?
SDEF data?
vertex group which stores the order of vertices?
other data?

In my opinion, it can be safer to add new mesh object if you want to add new geometry, and can be safer to "separate selection" in edit mode, [Mesh]->[Vertices]->[Separate]->[Selection] if you want to remove some vertices. SDEF data are not reliable after changing geometry in Blender, you may need to fix them in PMDE/PMXE.


Sort Vertices:

None: No sorting, the vertex sequence is defined by pmx exporter while gathering mesh data
Blender: sort vertices by blender's internal vertex order (and object order), [low -> high]
Custom: sort vertices by custom vertex weight of vertex group "mmd_vertex_order" (and object order), [low -> high]
