### ISSUE TITLE
Rigid body does not stay connected to bone?

### ISSUE THREAD

**Issue by NoelShourai** [powroupi/blender_mmd_tools#176]
Hi,

This is probably because I have no idea what I am doing, but when I try to add a rigid body to an existing model, the rigid body never stays attached to the corresponding joint and falls straight down, or explodes and flies outside the scene. The result looks like cloth or hair stretching through the floor or spazzing out.

Is there something I am forgetting to do?

**Comment by Hogarth-MMD** [comment]
All physics rigid bodies will fall under the force of gravity. So the rigid body at the top of the chain of rigid bodies must not be a physics rigid body.

**Comment by NoelShourai** [comment]
I'm not quite sure I follow. So I make the first bone of the rigid body chain a non-physics rigid body bone, or the root preceding the chain (i.e. the root joint of an array of multiple bones, i.e. the root bone of a skirt) must be a non-physics rigid body bone?

Either way, regardless of how I try to approach it something like the following still happens.

![image](https://user-images.githubusercontent.com/19917103/46063416-c14b4680-c13a-11e8-9ff2-75aeeec7dc62.png)

**Comment by Hogarth-MMD** [comment]
I just tried physics rigging of a skirt for the first time in Blender. You need to be reasonably expert with Blender and mmd_tools to succeed with it. Making a selection of the skirt bones (only) is kind of a pain. Making a selection of the skirt and lower body rigid bodies (only) is also kind of a pain. 

mmd_tools does mass physics rigging and those tools seem to work fine. Just select all the skirt bones and click + beside the mmd_tools Rigid Bodies panel to mass add rigid bodies (Physics type rigid bodies). Select the lower body bone to add a rigid body to it (Bone type rigid body). Select all skirt rigid bodies AND the lower body rigid body and then click + beside the mmd_tools Joints panel to mass add joints to the rigid bodies.

If the skirt rigid bodies "explode", that happens because the rigid bodies are too large. They are overlapping each other and they need to be scaled down. In Blender, you need to choose the center of scaling before scaling something. The center of scaling should be "Individual Origins". You can select all of the skirt rigid bodies and scale them simultaneiously.

If the skirt rigid bodies are falling to the ground, that has 2 possible causes that I know of:
1. The rigid body of the lower body bone must be Bone type, not Physics type.
2. Somewhere in the chain of rigid bodies, a pair of rigid bodies does not have any joint connecting them. You need to be sure that every pair of rigid bodies is connected by a joint.

And you need to click on the Physics [Build] button after the physics rigging. Even if you have already clicked on the Physics [Build] button earlier in the physics rigging process, click on it again at the end of the process. 

At the bottom right side of the 3D view Window is the MMD Display panel which you can use to toggle on and off the display of Rigid Bodies, Joints, Mesh and Armature.

Here in the mmd_tools github wiki are tutorials, but as you can see, there is no physics-addding tutorial yet:

https://github.com/powroupi/blender_mmd_tools/wiki/Links-to-mmd_tools-Tutorials

**Comment by Hogarth-MMD** [comment]
After you have finished physics rigging, and you want to export your model from Blender, you should click on the mmd_tools Physics [Clean] button before exporting your model to .pmx.

**Comment by NoelShourai** [comment]
Tried it again. It's still not perfect, but it looks like the mistake I was making was that I forgot to establish a joint between the root bone and the starting bones of the physics chains.

Thanks!

![image](https://user-images.githubusercontent.com/19917103/46102972-a0680d00-c19d-11e8-96e7-db7e914a39d0.png)
