### ISSUE TITLE
Why i can‘t export any model to pmx

### ISSUE THREAD

**Issue by lianlianaa** [powroupi/blender_mmd_tools#193]
when i click the button that export pmx.
NO error tips，no  load wait，and no new file.
what can i do

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

In order to export a model to pmx, you have to select one or more MMD model(s) in Blender before clicking [Export] button. (select any one object of a MMD model to export it)

A MMD model which can be recognised by `mmd_tools` must have **a root empty object** created by [Create Model] or [Convert Model], with **an Armature object** to be the empty's child, and **Mesh objects** to be the Armature's children. Otherwise, `mmd_tools` can export nothing.

A PMD/PMX model imported by `mmd_tools` can always be exported without any problem. If you selected multiple MMD models, `mmd_tools` will export them to individual new folders by their root empty object's name.

If you want to export a rigged custom model, select its Armature object, then click [Convert Model] to convert it to a MMD model. Select any one object of the MMD model, then click [Export] to export it.

If you want to export a non-rigged custom model (only mesh objects), click [Create Model], then parent the mesh objects to the Armature object created by [Create Model]. Select any one object of the MMD model, then click [Export] to export it.

[Tutorial:-How-to-convert-a-3D-character-model-to-MMD](https://github.com/powroupi/blender_mmd_tools/wiki/Tutorial:-How-to-convert-a-3D-character-model-to-MMD) for further info. :smile:

**Comment by lianlianaa** [comment]
Thank you for your prompt response, it seems to be successful after following the instructions you said. Although there are still some minor issues, I will try to understand the amount of information you give to know what I should do next. Thank you once again
