### ISSUE TITLE
Camera problem in blender 2.8

### ISSUE THREAD

**Issue by TianZhongJun** [powroupi/blender_mmd_tools#196]
After I import VMD moiton to camera,the angle and perspective value of MMDCamera is always zero(Angle value is zero ,perspective value is false).and they even can't be changed.

use newest blender and addon.
![qq 20190108220656](https://user-images.githubusercontent.com/19504740/50835473-c0f55500-1391-11e9-9848-4892f75aebbd.png)

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

I don't know how to fix it yet, I'll keep tracking this issue. :smile:

**Comment by zeromizkun** [comment]
@TianZhongJun How did you manage to get MMD tools to work in Blender 2.8? I am unable with the way i've done with with 2.79 and others so far..

**Comment by TianZhongJun** [comment]
> 
> 
> Thank you for reporting this issue. 😄
> 
> I don't know how to fix it yet, I'll keep tracking this issue. 😄

Thank you for your reply.

**Comment by TianZhongJun** [comment]
> 
> 
> @TianZhongJun How did you manage to get MMD tools to work in Blender 2.8? I am unable with the way i've done with with 2.79 and others so far..

Just nomal install newest addon to newest blender.No other operation.

**Comment by zeromizkun** [comment]
> > @TianZhongJun How did you manage to get MMD tools to work in Blender 2.8? I am unable with the way i've done with with 2.79 and others so far..
> 
> Just nomal install newest addon to newest blender.No other operation.

Ay thanks, fixed it apparently it was because I didn't unblock the zip file before extracting :) works now!

**Comment by lwp513202035** [comment]
blender的景深系统和mmd里的工作模式可能不一样吧，mmd的镜头导进去后，是通过镜头绑定空物体，空物体在镜头聚焦的位置，来实现的。而且如你所说，导入后透视、焦距、景深、聚焦位置加旋转都有问题，唯一准的是位置信息。但是blender原生镜头的景深就是实际光学镜头的那些参数。所以可能需要一些比较复杂的转化之类的，但是现阶段插件作者也说不知道咋解决。我现在都是自己重新弄镜头的_(:з」∠)_而且通过多镜头和绑定曲线，我觉得虽然工作流程比mmd里复杂了，但是能实现的效果更多了。

**Comment by TianZhongJun** [comment]
> 
> 
> blender的景深系统和mmd里的工作模式可能不一样吧，mmd的镜头导进去后，是通过镜头绑定空物体，空物体在镜头聚焦的位置，来实现的。而且如你所说，导入后透视、焦距、景深、聚焦位置加旋转都有问题，唯一准的是位置信息。但是blender原生镜头的景深就是实际光学镜头的那些参数。所以可能需要一些比较复杂的转化之类的，但是现阶段插件作者也说不知道咋解决。我现在都是自己重新弄镜头的_(:з」∠)_而且通过多镜头和绑定曲线，我觉得虽然工作流程比mmd里复杂了，但是能实现的效果更多了。

不明觉厉。

**Comment by nathanvasil** [comment]
> 所以可能需要一些比较复杂的转化之类的，但是现阶段插件作者也说不知道咋解决

This seems strange to me.  There is a 1:1 correspondence between focal length and FOV in degrees.  Blender is happy enough to do this conversion itself, so there has to be a transformation function somewhere in the code, which is all open source.  (It doesn't seem linear, so interpolation would be different, but that's a small thing.)

https://www.blender.org/forum/viewtopic.php?t=12108 suggests where to look, and offers that Blender's FOV = 2 atan(0.5A/f) where A=32 and f=focal length.  Reworded, f = 16cot(FOV/2).  Testing this out for FOVs of 90, 45, 30 gives me appropriate focal lengths for use in Blender.

Although, personally, I don't need this feature-- I think that most MMD cameras lack any sense of restraint when it comes to FOV, so it's one of the first things I change in downloaded cameras, and if I wanted to make my own camera, I would find it easier to do so in Blender than in MMD.

Edit: I suppose if you wanted proper interpolation as FOV instead of as focal length, you'd create a custom value for FOV, interpolate that, and use it to drive focal length.  Not so hard.

Edit2: Should add, I was testing in 2.79, there's always a possibility this was changed in 2.8.

**Comment by powroupi** [comment]
@TianZhongJun I've update `mmd_tools` (`dev_test` branch), you might test it again, thank you. :smile:

**Comment by TianZhongJun** [comment]
> 
> 
> @TianZhongJun I've update `mmd_tools` (`dev_test` branch), you might test it again, thank you. 😄

Thank you very much, I will try it.

**Comment by TianZhongJun** [comment]
> 
> 
> @TianZhongJun I've update `mmd_tools` (`dev_test` branch), you might test it again, thank you. 😄

I had try it , problem has been solved。Thank you very much !
