### ISSUE TITLE
message for powroupi

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#204]
you can delete this issue after reading, @powroupi - I need to send you a direct-message

this is just about some content in this GitHub that I feel needs to be deleted. or you can send me an e-mail at <my github handle> AT gmail DOT com

**Comment by powroupi** [comment]
@ptrthomas yeah, totally agree with you, but I can't delete/edit some content for some reason, I'm not using latest browser supported by GitHub, sorry. :cry:

So for everybody who posted issues/comments, please delete/edit your comments which contain any improper content. Thank you very much. :smile:

**Comment by ptrthomas** [comment]
@powroupi oof. if you don't mind adding me as an admin user for a few minutes I can remove the screenshots that are not nice. but hope you eventually are able to get this fixed

**Comment by powroupi** [comment]
@ptrthomas how do I add you as an admin user? I've invited you as a collaborators.

**Comment by ptrthomas** [comment]
@powroupi actually that works, I think I can edit. but hey looks like you were able to do exactly what I was trying to do (see screenshot below) ! Is there any other item you want me to edit, else you can remove me as an "owner", thanks ^_^

<img width="537" alt="image" src="https://user-images.githubusercontent.com/915480/52913759-3f290d80-32e7-11e9-8a67-fa97d1a0f429.png">

**Comment by powroupi** [comment]
@ptrthomas yeah, but I can't view hidden posts, I can delete visible posts only. :cry:

**Comment by ptrthomas** [comment]
@powroupi hmm not sure I understand - for me it seems to be 100% gone - anyway thanks, I'm deleting this ticket now.

**Comment by ptrthomas** [comment]
can't delete it :)

**Comment by powroupi** [comment]
Thank you, I don't know if there is any other posts? I'll keep that permission for you.

Issues seems can not be deleted. ><

**Comment by ptrthomas** [comment]
@powroupi only admins can do it it seems: https://stackoverflow.com/a/53195537/143475

**Comment by powroupi** [comment]
No, I don't see any delete button. :(

**Comment by ptrthomas** [comment]
@powroupi ok no worries. thanks for the permission. promise to use wisely 👍

**Comment by powroupi** [comment]
Oh, I got it.

**Comment by powroupi** [comment]
Do you want to delete this issue?

**Comment by ptrthomas** [comment]
@powroupi hmm actually, it is fine - you can keep this for now, thanks !

**Comment by Hogarth-MMD** [comment]
I am shocked very much that @powroupi would give to someone the power of mass deletion, just because that person asks to be given the power of mass deletion. @powroupi does not know that the person making this request is @ptrthomas . This request might be coming from someone who has hacked the account of @ptrthomas , for example.

Not once, but MANY TIMES, members of the MMD community have been the victim of mass deletion of their generous hard work. The most catastrophic example was the closing of the CitruSmoothie web site a few years ago. Apparently a few postings in this MMD blog violated the terms of service of the host web site, and this was turned into an excuse to mass delete several years of the hard work of the author of this blog .

I recommend to @powroupi to safeguard his own and other people's postings and hard work, with THE MOST EXTREME POSSIBLE CAREFULNESS AND WISDOM.

**Comment by ptrthomas** [comment]
nonsense. that's not how open-source works. but anyway, @powroupi please remove me as a collaborator. I have better things to do in life that to listen to this bullsh*t

**Comment by MuteObserver** [comment]
Full power to modify a project and it's settings on GitHub where it's hosted is not an inherent part of open source.

Intentions are hard to tell on the internet, and there's reason to be skeptical.
Things like that have happened before. I hope you can see that on the internet there's a due concern. Things like this are probably best done _without "letting go of the wheel"_ before you know somebody better. All was fine in this situation, you seem to have had your intentions straight, and haven't done harm. That's not the accusation here.

Like Hogarth probably is, I'm.. just **a little surprised** it was as easy as asking.
Not something you see so often.

**Comment by ptrthomas** [comment]
@IAmMute all wrong. 

- asked to be removed first (if you had only cared to read the whole thread)
- is not "full power", I would agree that would have been completely out of line
- thus nothing is ever lost, since open source. and there are forks for added measure

no need for you to agree - after all it is too easy for random people to come in and lecture others on open source, act all surprised, and feel good about themselves ^_^

**Comment by ptrthomas** [comment]
@IAmMute oh and just one more thing - @powroupi  and myself go back a long way. and he was perfectly justified IMO (doesn't matter if you disagree) to extend collaborator rights. there has been a fair amount of collaboration and exchange of ideas in the past. and by now I assume he would have developed a certain level of trust. I have contributed to this same project via pull-requests and feedback, especially the english translations. which involved a fair amount of work with google sheets, and personally [one of the best real-time collaboration experiences I have ever had](https://github.com/powroupi/blender_mmd_tools/issues/61#issuecomment-310852104). 

Okay, here's a little lecture from my side - think about it - there is ALWAYS the risk that someone will get through the system and there is NO WAY to prevent this. consider these scenarios:

- what if someone has hacked @powroupi -s account ? how the f would you know ?
- suppose I was a legitimate collaborator from the start and had been for 5 years. what is the guarantee that I would not "turn rogue" one fine day ? or someone threatened me or blackmailed me ?

geez.

**Comment by MuteObserver** [comment]
I think this is getting.. a little out there. Heated, almost.
_I'm not particularly strong on this being an issue_. It's not the end of the world. 

- The "whole thread" is a short scroll-down. Rest assured, it's been read.
- How is anybody to know what relationships are going on behind the scenes? This is unrealistic.
- Appealing to the unknowns of security just deflects from what we're looking at. Separate issue. Sure; zero-days are everywhere, many people don't secure things, it's not out of the cards and I'm sure nobody would know until the damage is done -at least the damage wasn't out of negligence, or leniency in who's placed into the admin team. Evidently there wasn't the risk because you had a history.

**That** wasn't made obvious from this **post;** perhaps I jumped the gun in that area. I can entirely admit fault there. Most of my post was me mentioning **where** I could see the point Hogarth was making.

That personal history you have can explain things, **and fair enough**; but to any unknowing observer what do you expect them to see? That's the core of what's being seen, and what was being reacted to. That's the bigger picture for anybody else.

You've responded quite immediately with a sort of lash-out. 
If it's all a misunderstanding surely you could take a few breaths.
End of the day: I was never coming at you, man.

I don't know what tone you read my post in, but I didn't write it that way.
Hopefully we can leave this here.

**Comment by ptrthomas** [comment]
@IAmMute hey okay, now that I've had time to take a deep breath. I'll admit that I did get over-triggered. I think I've made myself clear - I especially take offense that despite all I tried to do in good faith - and requesting to be removed as an admin etc - I get this reaction.

you make a good point that you don't have history and how were you supposed to know etc. I can turn the question back on you - because what really triggered me here is how easily you got swept up in our dear friend @Hogarth-MMD -s rabble rousing, inflammatory statements and BS call to arms.

Exhibit A: 
https://github.com/powroupi/blender_mmd_tools/issues/182#issue-380331870

and I quote below:

> I have absolutely no plan or intention of updating mmd_tools_helper add-on every time that @powroupi feels like behaving in this dictatorial, unpredictable, discourteous and inconsiderately time-wasting way.

There are many other examples. I think I made my point. so peace. all is good between you @IAmMute and me ^_^

**Comment by powroupi** [comment]
>@powroupi please remove me as a collaborator.

Okay, @ptrthomas, I've remove you as a collaborator now.

Let me know if you need permission to delete any post, I'll try my best to help you. I'll trust you and I don't think there is anyone who need or want to ruin this repository. :)
