### ISSUE TITLE
There is something wrong with the motion import.

### ISSUE THREAD

**Issue by lwp513202035** [powroupi/blender_mmd_tools#205]
Hey, powroupi, I have problem again_(:з」∠)_. @powroupi 
I try to use the motion from https://www.youtube.com/watch?v=pdenALKNA8w , it works well in MMD , but when I import the motion into a MMD model in Blender, it goes wrong. 
<a href="https://imgchr.com/i/ACQTlq"><img src="https://s2.ax1x.com/2019/03/11/ACQTlq.md.png" alt="ACQTlq.png" border="0" /></a>
Is there any way to solve it?

**Comment by lwp513202035** [comment]
I update the addon and it works well now , sorry for bother. But by the way , I found that when the motion of a model or camera were import into Blender, it often delayed 6 frames. Is there any way to make  it start from frame 0?

**Comment by nathanvasil** [comment]
When you import a motion, there should be an operator panel in the lower left corner of the file dialog where you can set import parameters.  One of the import options is "margin" which creates the delay you're noticing.  The reason for this delay is to give any physics objects a chance to settle down before starting the animation.  But you can feel free to enter 0 in the margin if you want.

**Comment by ptrthomas** [comment]
@nathanvasil @powroupi personally I ALWAYS set the margin to 0 - I'd like to request making this the default - because I've never found any good reason to have a margin

**Comment by nagadomi** [comment]
@ptrthomas 
You can save import/export settings to the preset. However, it will not be the default value.
@powroupi 
I think that it is better for import/export settings to be stored in AddonPreferences and set to the default value.

**Comment by powroupi** [comment]
Okay, I think I'll change the default value to 0 next time. :smile:

@nagadomi, there would be a lot of getter/setter functions if we store default values of import/export settings in AddonPreferences, so I prefer to simply change the default values in `operators/fileio.py`. :)

**Comment by nagadomi** [comment]
>I think I'll change the default value to 0 next time.

When margin 0, motion that moves the root bone in the first frame(e.g. motion for multi person) causes problems in physics. 
I think the default needs to be a value that doesn't cause any problems.

**Comment by lwp513202035** [comment]
@nagadomi I think that maybe  you move the all the frames -1 after you import motion into blender if you set the margin=0 can solve the problem.

**Comment by nagadomi** [comment]
I care about people who use mmd_tools for the first time. They will think that this addon does not work if it does not work with the default settings.

**Comment by ptrthomas** [comment]
> When margin 0, motion that moves the root bone in the first frame(e.g. motion for multi person) causes problems in physics.

maybe but I've honestly never faced this problem.  I find it irritating to set margin to 0, and when I forget it (many times), you have the same problem reported by this new user @lwp513202035 - that the model "jumps" into some pose in 5 frames - so you need to consider that this was reported by a new user. I also doubt that people new to blender will be starting with multi-person. and again, I have done multi-person and never seen this problem.

we can leave this to @powroupi to decide

**Comment by nathanvasil** [comment]
Is it possible that there might be some better way to handle this anyways?  5 frames isn't enough for physics to settle down, but multi-model motions are often used by beginners for single models, using just one of the motions, and some single model motions jump off the world origin anyways; even when they don't, motions don't bother transitioning from unposed to pose at frame 0, physics are never right.

I just did a few tests to see if there was something else that could be done.  I made a simple pendulum.  On frame 1 and 2, I keyframed animated and a constantly interpolated visual child-of the constraining rigid (the anchor body) for the physics body. On frame 3, I keyframed animated off and reset its position to its default (from a delta I set-- it would be kind of nice if MMD Tools set delta transforms for physics.)  On frame 1, I jumped the anchor body's bone to a new place.  This seems to prevent any kind of physics jump whatsoever.

It needs to be have the animated property set for two frames to zero out its velocity.  But here we have 2 or 3 frames margin necessary to reset all physics.  (Physics being off for the first frame strikes me as fine.)  Because there aren't actually any physics going on, this could probably be cached without requiring any time, and it might be possible to do so at motion load; it may even be possible to set this to negative frames, or it may be possible to set the current frame and frame range start to an appropriate value.

I'm not totally sure how doable this is, and it was just a simple experiment, but it could make both nagadomi and ptrthomas (each of whose views are probably representative of many other users of MMD Tools) happy.

**Comment by powroupi** [comment]
There are 2 situations I can think of: (actually margin=5 is reasonable)
1. [Import] model -> [Build] physics -> [Import] motion. It may cause problems in physics when the margin is set to 0.
2. [Import] model -> [Import] motion -> [Build] physics. No matter what the margin is, it should work fine, but I'm not sure if there is any bug in calculating the initial position/rotation of rigidbody/joint objects.

By the way, you could try keyframing the **speed** value of [Rigid Body World] to workaround the physics jump. For example, keyframe **speed=100** at first frame, and keyframe **speed=1** at the frame where the action actually start, so the physics can settle down quickly. :smile:

**Comment by lwp513202035** [comment]
> By the way, you could try keyframing the speed value of [Rigid Body World]

@powroupi 
I find that when blender deals with some model in a big shape, the speed of rigid body becomes someway a little unnatural. Like a MMD model imported into blender, when the world length unit is set to meters, the default sacle of the model is very large, and the speed of rigid body is a little slow.

Is there any help if I change the world unit to centimeters  or set the speed to a higher value like 2 or 4?  Actually I am not sure whether the speed is normal or not , but when  I watch the final render animation , the performance of the rigid body is not as well as in MMD . And every time to make a attempt cause much time , so I want some suggestion before I try to figure it out _(:з」∠)_.

**Comment by powroupi** [comment]
@lwp513202035, you need to import model with scale (about) 0.2, the result will be ok. If you import model with scale 1.0, then you need to change [gravity](https://docs.blender.org/manual/en/dev/physics/gravity.html) to **-9.8*5** or scale the root object size down to 0.2 to get better physics result.

**Comment by nathanvasil** [comment]
>For example, keyframe speed=100 at first frame

If you also pump up the steps-- otherwise you're going to have rigid bodies getting caught on the wrong side of colliders that they jump through thanks to your physics speed (like hair and heads, skirts and legs.)

**Comment by powroupi** [comment]
Here is another way to make the physics settle down quickly:
1. [Import] model (with scale 0.2) -> [Import] motion (with scale 0.2, margin 5).
2. At first frame, select armature object, change to Pose Mode, [Pose]->[In-Betweens]->[Pose Breakdowner] (Shift+E)  about ~100% to get the starting pose, then adjust the pose to minimize its physical impact (minimize the impact between the initial pose and the starting pose).
3. In `Morph Tools` panel, [Add] a bone morph, then [Apply] current pose to get the selection of bones which have offsets, and then insert [LocRot] keyframes to those bones to replace the initial pose.
4. [Build] physics, then play, margin 5 should be enough. You can also play the physics settings to get better result. :)
