### ISSUE TITLE
Weird Rigid Physics behavior when Main empty is move?

### ISSUE THREAD

**Issue by ikumi90s** [powroupi/blender_mmd_tools#21]
Hi, I just pull up the latest version and tried to play my Miku animation which has stationary skipping animation.... when I tried to move her position using the main empty the physics goes nut, here is an example of the problem : https://www.youtube.com/watch?v=gfoR3-DElyM

instead the rigid physics flows with the animation. moving her to front and back makes the physics move somewhere else, I cannot find any particular place where the problem occur please help...

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I think it's normal, just like the bone issue of [master branch](https://github.com/powroupi/blender_mmd_tools/tree/master) which is solved in [dev_test branch](https://github.com/powroupi/blender_mmd_tools/tree/dev_test). That is because we use `Child Of` constraint on static rigid bodies to follow their target bone, you can toggle the visibility of rigid bodies to see the effect when you moving main empty. :)

And sorry, i'm still looking for a way to solve it (in script). :sweat: 

If you really need to move main empty, after building the model, you can try parenting static rigid bodies to their target bone manually and mute `Child Of` constraints, and re-parenting them to the empty object `rigidbodies`(which is a child of main empty) manually before cleaning the model.
- Parenting rigid body object to bone:
  1. RMB select armature object, switch to pose mode
  2. RMB select rigid body object, Shift+RMB select pose bone, Ctrl+p choose `Bone`
- Re-parenting rigid body object to object `rigidbodies`:
  1. RMB select rigid body object, Alt+p choose `Clear Parent`
  2. Go to outline window, LMB (click +) expand main empty, LMB drag rigid body object (which should be outside of main empty) to object `rigidbodies`

**Comment by ikumi90s** [comment]
Oh I see it's an current issue...
Thanks for the tips, I'll try it :)
I will let you know if I have any workaround if I see a fix in my current project. T_T
Thanks.

**Comment by powroupi** [comment]
Great! I think the issue should be solved now, also improved the performance of "Build" function. :)

Have fun. :smile:

**Comment by powroupi** [comment]
Does the issue not being solved or any further issues? You can close this issue if you don't see any further issues. :smile:
