### ISSUE TITLE
Texture problems on Sour style Rin, Len and Luka models

### ISSUE THREAD

**Issue by KianaDaEditor3701** [powroupi/blender_mmd_tools#214]
I'm trying to use Sour-style Rin model on Blender but the textures are rendered incorrectly... Maybe some sort of nothing nut bugs on the add-on itself...

Material view: 
![Material View](https://user-images.githubusercontent.com/40626713/56466470-281cae00-6445-11e9-974c-749ae18bb6f4.png)

Texture view:
![Texture View](https://user-images.githubusercontent.com/40626713/56466477-4b475d80-6445-11e9-9aa3-da5a77f7d4b1.png)
<sub> *note the transparency of the texture is "masking" something below it* </sub>

Rendered result: <sub> *(rendered at 1920 × 1080 with default rendering parameters)* </sub>
![Rendered Result](https://user-images.githubusercontent.com/40626713/56466486-7cc02900-6445-11e9-8034-d4adc8630b9a.png)

Any help?

###### p.s. this error doesn't seem to appear on Miku; and models for Len and Luka have these issues too...

**Comment by nagadomi** [comment]
Regarding the rendering result, it is [z-fighting](https://en.wikipedia.org/wiki/Z-fighting) artefact. Cycles seems to have this problem.
This happens because the mesh for the blush(赤面) morph overlaps the face mesh. It can be fixed by slightly shifting the blush mesh.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile:

I'm assuming you are using Cycles render engine. It's not a bug, it is because there are overlapping faces on the mesh itself, and Cycles renderer can not render overlapping faces properly. It can be solved by giving tiny distance between the overlapping faces. :)

- Select the mesh object, go to Edit mode, deselect all vertices
- Go to material slots, click material "照れ"(Blush), click Select button to select those faces using this material. In 3d view, move the selected faces/vertices tiny distance along global -Y axis.
- Also do the same thing for "照れ２"(Blush2) and other overlapping faces.

**Comment by KianaDaEditor3701** [comment]
Thanks for the help. It's too daunting to manually fix the texture meshes...

**Comment by nathanvasil** [comment]
There are other ways that might be less daunting, CV.

When I need a slight displacement from two otherwise identical meshes, I use a displacement modifier.  Separate by materials (using the MMD button if you want.)  Now all the materials are their own meshes.  Select the blush object and add a displace modifier on properties/modifiers.  Set the mid-level to something like 0.999 and leave the rest of the modifier's fields at default.

If there are other meshes like this as well, add displace modifiers to them as well.  You may need slightly different amounts of displacement (0.998, 0.995, whatever, anything works) if you have multiple meshes with coplanar faces.
