### ISSUE TITLE
How can I export abc file without rigidbody?

### ISSUE THREAD

**Issue by qsqsaaw** [powroupi/blender_mmd_tools#236]
When I have exported an abc file on blender 2.8 with mmd_tools ,the abc file have rigidbody in it.
When I export an abc file on blender 2.79 with mmd_tools ,the abc file doesn't have rigidbody in it.
How can I export abc file without rigidbody on blender 2.8?

**Comment by powroupi** [comment]
I have not used abc files yet, you might try enabling some [Export Options](https://docs.blender.org/manual/en/latest/pipeline/alembic.html#scene-options): [Selected Objects Only], [Renderable Objects Only], [Visible Layers Only].

I think it is because MMD rigid bodies are Renderable Objects, they will be exported if you only enable [Renderable Objects Only] option. So you might try selecting only the mesh objects you want, then export abc with [Selected Objects Only] enabled. Thank you. :)

**Comment by qsqsaaw** [comment]
It is works that I checked [Renderable Objects Only]and[Visible Layers Only],there is no more rigidbody in abc file. Thank you a lot!
I can't imagine why. What is layers. Is any rigidbody on other layers?

**Comment by powroupi** [comment]
You're welcome. I guess it basically export visible objects of visible collections/layers, so rigid bodies might be exported if you unhide them. Anyway, I'm glad this issue is solved. :smile:
