### ISSUE TITLE
Physics collider in ue 4

### ISSUE THREAD

**Issue by Follzen** [powroupi/blender_mmd_tools#241]
if you export a model with physics and animation to FBX and import it into Unreal Engine 4, physics triggers appear in the form of cubes and other debris

**Comment by powroupi** [comment]
You might deselect everything and only select the Armature & Mesh objects you want to export in 3D viewport, and then export to FBX with export option **[Selected Objects]** enabled (might also disable object types `Empty/Camera/Light/Other`, leave only **Armature/Mesh** enabled), otherwise, MMD rigid bodies / joints might be exported.

Not sure if it works for you or not, I think this might not be an issue or bug related to `mmd_tools`. :cry:
