### ISSUE TITLE
When i import a PMX model into blender the statement "file signature is invalid" appears

### ISSUE THREAD

**Issue by Bosseekong** [powroupi/blender_mmd_tools#244]
https://gyazo.com/eb568df7a973dcf59fc5378b57b16d06 when i try to import files like this one https://www.deviantart.com/mikumikuknight/art/Beast-Titan-dl-717664051

**Comment by nagadomi** [comment]
mmd_tools you installed seem to be an old version.
uninstall it and reinstall the latest mmd_tools from https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip

background: it is a intentional corruption technique that prevents loading the model on PMXE. The latest mmd_tools seems to ignore errors due to it.
