### ISSUE TITLE
Is it possible to convert MMD shader to Principled BSDF shader?

### ISSUE THREAD

**Issue by Vwings** [powroupi/blender_mmd_tools#248]
Some pmx model loses toon files, and the material appears as pink color when imported into blender, maybe it will be better to support converting MMD shader to Principled BSDF.

**Comment by NaughtDZ** [comment]
That's true. Give us at least one choice.  Pink toon material is really uncomfortable

**Comment by powroupi** [comment]
You can start an empty scene -> add an simple mesh object -> add a material to the mesh object -> change alpha value of *MMD Material*, and start to tweak nodes of **MMDShaderDev** & **MMDTexUV** in Shader Editor, then save it as a version of your startup file.

Since we don't know what result you preferred, you have to tweak nodes by yourself. :cry: 
**MMDShaderDev** has most inputs you need, you can disconnect links, remove/add nodes inside this node group, as long as you don't remove the default inputs & output, it won't break `mmd_tools`. :smile:

For example, inside **MMDShaderDev**, you can simply add a Principled BSDF, connect [Base Tex] to the [Base Color] input of Principled BSDF, and connect the output of Principled BSDF to group output to replace it. It will globally change the materials/shaders which use this node group.

Click the [users] number of **MMDShaderDev** node will make a new node group copy, so you can use different versions for different materials. :smile:

**Comment by zhouhang95** [comment]
Why I use blender rather than mmd?
For better render results.
If using default shader, why not use mmd directly.
Now, there are a lot of materials need to modify if using BSDF

**Comment by zhouhang95** [comment]
I think most people have same idea with me.
Maybe we should discard the old mmd shader in blender.
if someone need to use default shader, modifing  in PE is the best way.

**Comment by nathanvasil** [comment]
If somebody wants to make their own material, there's nothing stopping them from doing that, and having an existing material with the texture node inputs is a useful start.

The default Cycles conversion isn't particularly the same as the MMD shader (which is terrifically painful to implement in Cycles).  Removing it would do nothing to make it any easier to create a custom shader.  Its existence means that workbench (texture view), eevee, and cycles all have reasonable shaders for editing.

While improved materials are a good use of MMD Tools, there are plenty of other reasons to use it.  Creating models for MMD, creating/tweaking/editing animations, modifiers that allow modelling/animation effects not possible in MMD, etc.

If you're having problems from toons, you probably need to specify your shared toon folder.  Many mmd models use "shared toons" that are contained in the data folder of your MMD directory.  (Or else, if you've already done that-- have you?-- maybe that feature isn't working right?)

**Comment by NaughtDZ** [comment]
> You can start an empty scene -> add an simple mesh object -> add a material to the mesh object -> change alpha value of _MMD Material_, and start to tweak nodes of **MMDShaderDev** & **MMDTexUV** in Shader Editor, then save it as a version of your startup file.
> 
> Since we don't know what result you preferred, you have to tweak nodes by yourself. 😢
> **MMDShaderDev** has most inputs you need, you can disconnect links, remove/add nodes inside this node group, as long as you don't remove the default inputs & output, it won't break `mmd_tools`. 😄
> 
> For example, inside **MMDShaderDev**, you can simply add a Principled BSDF, connect [Base Tex] to the [Base Color] input of Principled BSDF, and connect the output of Principled BSDF to group output to replace it. It will globally change the materials/shaders which use this node group.
> 
> Click the [users] number of **MMDShaderDev** node will make a new node group copy, so you can use different versions for different materials. 😄

Maybe you can add a switch option: use the principled / MMD material, and if you choose the "principled"option, it will use only the diffuse texture and the principled BSD. It's painful to modify the material manually from MMD material one by one.

**Comment by nagadomi** [comment]
@NaughtDZ 
You can edit MMDShaderDev. All materials use the same group node, so there is no need to modify the materials one by one. (link to similar issue #183 )
