### ISSUE TITLE
traceback error while exporting to PMX

### ISSUE THREAD

**Issue by ebababa** [powroupi/blender_mmd_tools#250]
i'm aware there's been dozens of traceback error reports and whatnot, but i haven't seen any for this specific one, and i've been stuck on it for a while. i spent a few days on a model and when i tried to export it last night just to test it, i got this:

![image](https://user-images.githubusercontent.com/55774654/65565741-d231c200-df1e-11e9-80ac-95c1a495cccf.png)

_Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\mmd_tools\operators\fileio.py", line 505, in executeself.do_execute(context, root) File "C:\Program Files\Blender Foundation\2.79\scripts\addons\mmd_tools\operators\fileio.py", line 522, in_do_execute_orig_pose_position = arm.data.pose_position AttributeError: 'NoneType' object has no attribute 'data'_

so, i'm pretty lost. i made a model a few weeks ago and didn't have any problems, and i just exported a cube and opened it in PMXEditor without any issues, so really i have no idea what the problem is.

i made sure my mmd tools is up to date and everything also. 
any help is appreciated, thanks.

**Comment by powroupi** [comment]
A MMD model which can be recognised by `mmd_tools` must have a **root empty object** created by [Create Model] or [Convert Model], with an **Armature object** to be the empty's child, and **Mesh objects** to be the Armature's children. Otherwise, mmd_tools can export nothing or raise errors.

I think the armature object of your model is missing. Make sure you have the following structure:
- Root object
  + Armature object
      + Mesh obejcts

See similar issue powroupi#193.

**Comment by powroupi** [comment]
Fixed in latest `mmd_tools` https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip :smile:
(see https://github.com/powroupi/blender_mmd_tools/commit/6a2eb7d0e6d40e1af222ce131e93089fd792c66e#diff-4d6964495c2995ce4e2354e6c04132c0)
