### ISSUE TITLE
Rotational appends not being treated appropriately by Blender

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#26]
http://www.mediafire.com/download/ebeh9jk12dfp2al/betterhalf.pmx

Load it up into PMXE/transform and rotate R_hipZBase.  The structure uses a -2.0 rotational append on R_hipZExtender to move R_hipXZ in the X axis when R_hipZBase is rotated in the Z axis.  Notice how the hip stretches when rotating R_hipZBase.

Now load it into Blender and enter pose mode.  Rotate R_hipZBase in the Y axis (due to axis differences between MMD and Blender).  Doesn't behave the same-- looks like the rotational append is using only a -1.0 influence, even though MMD Additional Transformation lists the rotation append properly at -2.0.

Can't play around with this more, because it gives me a mysterious message when trying to edit the transformation influence: "Changes has not been applied."  Not sure how to apply the changes to see exactly how MMD Additional Transformation impacts bone rotation.

**Comment by powroupi** [comment]
Okay, it should be a limitation, we can only use the influence in the range -1 to 1 in blender (although the property range can be changed freely). I'm not sure if there is any way to solve it... >_<

> Can't play around with this more, because it gives me a mysterious message...

After changing the values in "MMD Additional Transformation" panel, you will need to hit the button "Apply" of "Bone Constraints" in "Operator" panel of "mmd_tools" to take effect. (Maybe it is better to update automatically...) :)

**Comment by nathanvasil** [comment]
Really?  -2 influence is so handy in MMD.  For the reasons demonstrated.  (Also, nice to be able to use 2.0/0.5 rotation appends to constrain to -90 to 90 degree angles.  Used this to create a tick action on the minute hand of a clock...)

I don't really see the point to requiring apply, but I'm still learning a lot.

**Comment by powroupi** [comment]
> I don't really see the point to requiring apply...

Now, the changes will be applied automatically in pose mode, it's a simple feature. :smile:

**Comment by powroupi** [comment]
Well, I think this issue is basically solved now. :smile: 

But "R_hipXZ" has a new problem. Maybe the shadow bones don't work as expected in some case. :(

To fix it in blender, you can align the bones to prevent the use of shadow bones:
1. Go to edit mode
2. Disconnect "R_hipZExtender" from "R_hipZBase" (disable "Connected" in bone "Relations" panel)
3. Change tail position of "R_hipZBase" to (head.x, head.y, head.z-0.1). (align to "R_hipXZ")
4. Go to pose mode
5. In the "Operator" panel of "mmd_tools", hit "Clean", and then "Apply" to re-apply "Bone Constraints"

Now, it works as expected. :sunglasses:

**Comment by nathanvasil** [comment]
Cool, thanks!

Yeah, even in MMD, the whole measurement structure doesn't quite do what I'd like it to.  Won't work as expected in some cases, as you say.  Still, appends > 1 are useful for a wide variety of structures.  Thanks for taking a look.
