### ISSUE TITLE
Duplicated mmd_bone.bone_id

### ISSUE THREAD

**Issue by nagadomi** [powroupi/blender_mmd_tools#269]
original report: https://twitter.com/uiiu714/status/1234717526224826369

`mmd_bone.bone_id`(MMD Bone Tools > ID) is assigned a unique ID(>=0) when the bone is used in Morph Tools panel. However, when copy a bone that is already used in Morph Tools, bone_id will be duplicated. Bones with duplicate bone_id cannot be selected in Morph Tools > Bone Offsets.

**Comment by powroupi** [comment]
It's a known issue just like #20 , and https://github.com/powroupi/blender_mmd_tools/issues/165#issuecomment-409508052.

- Duplicated mmd_bone.bone_id affects bone morph and bone appends (rotate+ , move+). Duplicating blender bone will cause the issue of bone_id (and maybe other issues of duplicated MMD Bone data when importing VMD or exporting PMX).
- Duplicated mmd_material.material_id affects material morph. Duplicating blender material will cause the issue of material_id.

To fix this issue, users will need to reset the id of newly duplicated bone or material. I just made a change so that users can fix id from UI panel now. Another way is to use Blender Python Console.
```python
# when select a pose bone
>>> C.active_pose_bone.mmd_bone.bone_id = -1
# when select a object, select a material slot
>>> C.object.active_material.mmd_material.material_id = -1
```

**Comment by nagadomi** [comment]
Hi. I am glad that you look well. :smile:
I think that change is enough to close this issue.
It's best to use the blender's internal ID and convert it on export, but it will change a lot.
