### ISSUE TITLE
Model import crashes 2.82 running with --debug command line

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#273]
This is kind of a weird issue.  Maybe a bug with Blender instead, not sure.

When running current 2.82 release, from devtest MMD Tools just downloaded, on Win10, running Blender with the --debug command line, Blender, importing a model (from the import button on the sidebar) crashes Blender reliably.  Tested with multiple models, including the Miku)Hatsune.pmd distributed with MMD install.  Tested with all addons disabled + restore factory settings in Blender.

I'm sure there's probably some additional information that can be gathered regarding this, but I'm not sure how to collect that information.

The workaround is pretty obvious: don't run Blender with the --debug flag.  (I had it set for some other issue I was dealing with, can't even remember what.)

BTW, the current devtest download file name doesn't have any file extension when downloading as .zip.  Small issue, but people have been stymied but smaller things.

**Comment by powroupi** [comment]
Yes, I can confirm it and found the workaround as following:
 - Open Blender (without --debug)
 - Import the pmd file of default Miku model
 - Click [Create] button of [Edge Preview:] under `MMD` Operator panel
 - Save this to `test.blend`
 - Close Blender

Then:
 - Open Blender using command: `blender.exe --debug`
 - [File] -> [Append] -> `test.blend` -> [NodeTree] -> Select All -> Append [MMDEdgePreview] & [MMDShaderDev] & [MMDTexUV]
 - Import your PMD/PMX file, it should work fine now. :smile: 

I'm not sure why Blender crashes in debug mode while generating node groups from `mmd_tools`, so we need to append those node groups created by `mmd_tools` to prevent this issue in debug mode. It works fine without the --debug flag though. Hopefully it can be fixed in the future. :)

>BTW, the current devtest download file name doesn't have any file extension when downloading as .zip.

It might be the configuration of your system (ex: file browser), the file extension is hidden by default on Windows, but I'm not sure what the exactly setting is... :cry:

**Comment by nathanvasil** [comment]
Yeah, it's not like it's a big issue, probably not worth fixing if nothing else is being impacted, just worth being aware of.  It's not really necessary to run with --debug enabled.

The .zip file was definitely not downloading with the file extension-- downloaded it twice, had to rename the file to extract it.  But re-downloading right now, the file has the proper extension.  Maybe my computer ate something that didn't agree with it; maybe Github did.  In any case, looks resolved now.

**Comment by powroupi** [comment]
Okay, it seems the way `mmd_tools` creates node groups was not ideal, so I did minor changes and the issue is solved now. You might test it again, and you can close this issue anytime if everything works fine. Thank you. :smile:

ps. #56, #207, #265 (crash when converting materials for Cycles) might be caused by this bug. Not sure :thinking: Hopefully this fix can solve those issues as well. :pray:

**Comment by nathanvasil** [comment]
Seems to be working fine with --debug now.  Would be cool if it solved those other issues (but I guess it's hard to tell since they were intermittent anyways.)
