### ISSUE TITLE
[proposal] add very basic shader for EEVEE as an alternative to MMDShaderDev

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#290]
I will contribute this code, but wanted to check with @powroupi and others here if this makes sense.

I don't know if this is just me but MMDShaderDev is very slow and unusable in EEVEE. So I would like to add an alternative, to start with - something like this - that comes close to the toon "shadeless" look and works well at least for older models:

this is some example code in `material.py`

```py
        ng = _NodeGroupUtils(shader)

        node_input = ng.new_node('NodeGroupInput', (-1, 0))
        node_output = ng.new_node('NodeGroupOutput', (2, 0))

        shader_trans = ng.new_node('ShaderNodeBsdfTransparent', (0, 1))
        shader_alpha_mix = ng.new_node('ShaderNodeMixShader', (1, 0))

        links = ng.links
        links.new(shader_trans.outputs['BSDF'], shader_alpha_mix.inputs[1])

        ng.new_input_socket('Base Tex', shader_alpha_mix.inputs[2])
        ng.new_input_socket('Base Alpha', shader_alpha_mix.inputs['Fac'])                        
        ng.new_output_socket('Shader', shader_alpha_mix.outputs['Shader'])

```

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/915480/83594144-17ad9100-a57c-11ea-8a39-31691b1542cf.png">

of course there is more work for toon-textures, and unusual masks and transparencies, but I thought it would be fun to do all that from scratch and learn. I even would like to get to a good toon-renderer including edge outlines if possible,

so I wanted to check if this sounds reasonable or am I missing something very obvious. I also plan to add a checkbox option in the import dialog file-chooser to choose this shader instead of MMDShaderDev

**Comment by powroupi** [comment]
I think we don't need to add any additional shader to `mmd_tools`, my idea is to let users tweak the node groups (MMDShaderDev, MMDTexUV) for their needs like you did now. :smile:

The next step is to save it to `sample.blend` file. You can [Append] the NodeTree inside `sample.blend` when opening a new project before importing .pmd/.pmx files. Another way is to directly save it as Blender's startup file ([File]->[Defaults]->[Save Startup File]), you may simplify it to only contains a cube with your custom MMD shaders. :)

Furthermore, users can create (or share) their own shader library, MMDShaderDev (default MMD shader) and some custom shaders (MMDSkin, MMDCloth, MMDGlass,...), so they can switch node group manually as they like for better render result. :smiley: 
(Some shader may require different MMDTexUV to work with, users can customize it freely as they need, maybe MMDSkinUV for MMDSkin, MMDClothUV for MMDCloth,...)

So, in my opinion, it's not necessary to code extra shaders in `mmd tools` side. :smile:

**Comment by ptrthomas** [comment]
@powroupi agreed. the append / startup blend file makes total sense. also I understand after some experimenting that each MMD model has wildly different needs. I do see that things like backface culling and alpha have to be manually set in some cases, maybe here there is an opportunity for the code to be improved.

I will close this. if you do happen to have some examples of a custom MMD shader please share, and any reading material to understand what the shader nodes are doing (toon tecture, sph etc)

thanks !

**Comment by nathanvasil** [comment]
I think what powroupi's saying makes sense.

The one thing where some further material support might be nice would be in edge outline, but in Eevee, it's tricky to get a good viewport preview for this because Eevee does not yet support true displacement.  (You can do a bunch of math and make a mesh, with displacement driven by render resolution, camera FOV, and camera distance; you can even get Animation nodes to handle mesh creation for you-- but it won't preview properly.)

But it's hard for me to imagine that Eevee will be without true displacement for forever, and it doesn't make sense to me to implement a really clunky version that can't be previewed when it'll be so much easier once Eevee has true displacement.  (Still probably won't preview perfectly, since it would need to depend on per-viewport resolution, but will preview a lot *better* because of access to per-viewport view vectors.)

Should also be said, I don't find MMD Tools' shaders to be slow (although I don't use them much) although of course your no-lighting emission render should be as fast it can get.  No shadow buffers needed....  Not exactly a toon shader, not the way most people mean it, however.

If you want fast, you might consider Workbench renders.

**Comment by ptrthomas** [comment]
@nathanvasil thanks, your comments are as informative as always. I'm certainly not an expert in any of this, but it is fun to learn. can you provide a link for me to understand "true displacement".

so you don't find MMDShaderDev to be slow ? that's a real surprise. I made one "discovery" that if I bypass some of the specular / reflect stuff - that fixes it, otherwise I get tremendous lag even in the viewport such that it is unusable. maybe it depends on the model as well. posting this (see screenshot below) in the hope that you may have ideas, or suggestions. this is the root cause of why I opened this ticket

oh yes my goal is a toon-shader, even if it takes a while. I'm inspired by this - there's a few references in the comments I mean to check out later: https://www.reddit.com/r/blender/comments/fzck0p/just_finished_making_my_anime_sniper_character/?ref=share&ref_source=link


![image](https://user-images.githubusercontent.com/915480/83716520-c40b7800-a64d-11ea-8049-7fb321ef8590.png)

**Comment by nathanvasil** [comment]
"Blender true displacement" gives lots of hits on Google.  It's just like a displacement modifier, but done in the nodes.  That gives you easy access to variables like camera distance to drive the displacement.  You enable it on materials/settings (in Cycles.)

> so you don't find MMDShaderDev to be slow ? 

I find it very difficult to create a shader that impacts viewport performance significantly-- that makes it so I can't smoothly orbit a static model.  It would probably be possible.  Right now, I'm looking at 70k verts with like 5 lights and really complicated shaders (that I made myself, that include a lot of unbaked procedural textures), and I'm getting at least 30fps.

> otherwise I get tremendous lag even in the viewport such that it is unusable

Are you talking about while posing?  That's not the shader, that's the damn armature modifier, which is terrible.  (Although I have read that Blender does some really crazy, dumb stuff to determine the tangent if you're using a normal map, so it's not impossible for the shader and posing to interact.)

As for your link, you should be looking at the use of shader to RGB node, which can let you turn a white diffuse BSDF output into any color-ramped thing you want.

**Comment by nathanvasil** [comment]
@ptrthomas 

![image](https://user-images.githubusercontent.com/19930899/83719950-ff298f00-a5ec-11ea-91ee-7571bd0cb5df.png)

That's the node group for my skin material up top.  Full res, so you can see I'm playing back in a viewport about 1440p.  43ish fps if I don't animate the armature.  (If I animate the armature, it all goes to hell.)

**Comment by nagadomi** [comment]
@ptrthomas 
In the latest mmd_tools, you can convert the default mmd_tools materials to simple matrials with `Convert to Materials For Cycles > Convert to Principled BSDF option`(left dialog, then restore engine to Eevee). `Edge Preview > Create` supports adding edge outlines using Solidify Modifier.

**Comment by ptrthomas** [comment]
thank you @nagadomi and @nathanvasil for the tips and references. aha the armature modifier eh. that kind of makes sense, I shall experiment.

**Comment by nathanvasil** [comment]
@nagadomi 

> Create supports adding edge outlines using Solidify Modifier

Doing things this way might be better than nothing, but the problem is that it creates outlines that are sized in world-space.  MMD's outlines (and Freestyle's) are sized in screen-space.  Actually, something not quite screen space, but very like it, because it's resolution dependent; it's a single pixel thick.  Maybe we should call it pixel-space.

Blender doesn't provide any tools for doing things in this particular space :)  So you have to do things in world space and convert.  But the conversion requires knowing where your "eye" is (usually, your camera, but not necessarily for a 3D viewport).  Edge lines that are further from the eye in world space, need a larger world space displacement/thickness. 

They also need to know the FoV and the output resolution.  Those aren't as important to get right for a preview-- they'll affect the edge line, but they'll affect all edge lines in the same way.  But the position of the eye can lead to vastly different edge lines, making thick what should be thin and vice versa, so it's something you want to get right.

However, I'm not even sure how true displacement would interact with eye inputs (might do some experiments) because I'm sure the displacement isn't per-viewport....

Edit: Looks like right now, in Cycles, true displacement values are calculated upon entering rendered preview or upon editing a node value, but they are not recalculated on changing dependent values (like camera position.)
