### ISSUE TITLE
Can't blink

### ISSUE THREAD

**Issue by gk2qf** [powroupi/blender_mmd_tools#352]
I found that if the model has two shape keys for left eye and right eye, and it has a combined shape key for blinking, then the left eye and right eye keys will not be added to the blinking keyframe when the movement(.vmd) is imported into mesh. What should I do?
![mmd bug0](https://user-images.githubusercontent.com/53642234/123436415-31939900-d601-11eb-95c3-fc5579d469b0.png)
![mmd bug1](https://user-images.githubusercontent.com/53642234/123436440-36f0e380-d601-11eb-82e8-aa492cee4f1d.png)

**Comment by gk2qf** [comment]
It can be resolved by merging two shape keys into a new shape key and renamed it. I think that maybe Morph Tools can do the same thing but I don't know how to use it. I try to create a new shape key from group with Morph Tools, but it does not work.
:(

**Comment by gk2qf** [comment]
It can be resolved in Blender by merging two shape keys into a new shape key and renamed it . I think that maybe Morph Tools can do the same thing but I don't know how to use it. I try to create a new shape key from group with Morph Tools, but it does not work.
:(

**Comment by gk2qf** [comment]
2.93.0

**Comment by nagadomi** [comment]
See #237 #294

**Comment by powroupi** [comment]
Assuming you have 2 vertex morphs (shape keys) `blinkLeft` and `blinkRight`.
![1](https://user-images.githubusercontent.com/9333484/123498991-16a74000-d666-11eb-8d25-4bce0cfbd450.jpg)

Create a group morph `blink`, add these 2 vertex morphs to group offsets, and then click [Bind] morphs.
![3](https://user-images.githubusercontent.com/9333484/123499000-245cc580-d666-11eb-873b-72e9b2e2e3e8.jpg)
![4](https://user-images.githubusercontent.com/9333484/123499005-29ba1000-d666-11eb-813e-a2f37e6e428d.jpg)

Make keyframes on the value of a group morph, then select the root empty object of the MMD model, and click [Export] VMD as usual.
(If your model has more then one mesh object which has shape keys, or has some morphs other than vertex morph. This way ([Bind] morph) is recommended in order to export a full VMD)
![5](https://user-images.githubusercontent.com/9333484/123499014-3d657680-d666-11eb-9416-714d53988428.jpg)
![6](https://user-images.githubusercontent.com/9333484/123499017-422a2a80-d666-11eb-97ef-040f15f14f90.jpg)

Now, you should be able to [Import] VMD to other MMD model which has a `blink` morph.
(If the `blink` morph is not a vertex morph (maybe a bone morph or other type), click [Bind] morphs first, then select the root empty object of the MMD model, and then import [VMD] to it.)
![8](https://user-images.githubusercontent.com/9333484/123499131-017ee100-d667-11eb-9778-193aa29a22ae.jpg)

**Comment by gk2qf** [comment]
> Assuming you have 2 vertex morphs (shape keys) `blinkLeft` and `blinkRight`.
> .........................................

It's just what I'm looking for!!!! Thanks!!!!!    :)
