### ISSUE TITLE
Clean Shapekeys Operator

### ISSUE THREAD

**Issue by Takuyax** [powroupi/blender_mmd_tools#354]
Hi!
After some update the mmd_tools.clean_shape_keys operator stopped being accessible by searching for it, and is still missing in the current version. Was there any intentional change to hide it? I guess it's normally used by "separate by materials" or something, but I use it very often for manual cleanup.

Would it be possible to get it added to the interface somewhere, or at least have it searchable again?

I'm currently accessing it by running `bpy.ops.mmd_tools.clean_shape_keys()`, but that's a bit of a hassle.

**Comment by powroupi** [comment]
Blender 2.90+ only search menu items, that's why some operators can't be searchable. I've added `Clean Shape Keys` to [Object] menu (4ee4723), so it can be searchable in Object mode now. Update your `mmd_tools` and try again. You can close this issue if there is not any flaw with this new updates. Thank you. :smile:

**Comment by Takuyax** [comment]
Awesome, that's perfect. Thank you!
