### ISSUE TITLE
After VMD import with English bone names - how to do an FBX export of the animation properly

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#37]
@powroupi  as you said, importing a VMD is fine, the jp name on the property is being used.

I have a problem when now using the Blender "export to FBX" utility to export the animation.

When I look at the Dope Sheet / Graph Editor - I see all the japanese names for the animation data.  So I think I need to convert these also.

Any suggestion where would be a good place to do it ?  Maybe an option on VMD import ?

**Comment by powroupi** [comment]
No, you don't need to convert them, that's because VMD importer use the bone names of VMD file as the group names. If we use blender's bone name, it wil be fixed. (reference **mmd_tools.core.vmd.importer.VMDImporter.__assignToArmature()**
in `bone.keyframe_insert(...`, change

``` python
group=name,
```

to

``` python
group=bone.name,
```

) :)

The only thing is that we don't convert shape key names yet, and it might not be easy and need to consider more. :thinking:

**Comment by ptrthomas** [comment]
Great.  Just a couple of questions:
- what is a "group name" is this a blender thing
- I can make this change, are you saying this change is ok to merge into the main project, and it won't affect anything else

**Comment by powroupi** [comment]
- Yes, it is blender thing, in Graph Editor, you can group several fcurves and make a name you like. :)
- Yes, it is ok, changing the group names won't affect anything about this addon. :)

P.S. Your contribution is still not shown, i guess it is because the name of your commits is `Peter Thomas`, you might need to change it to `ptrthomas` (maybe change the user name of git config). :smile:

**Comment by ptrthomas** [comment]
Thanks @powroupi I'm making the above change and also a couple minor changes to the bone name mappings.  Need a couple of days.

BTW thanks for the tip, it is the e-mail ID you use for your check-ins that is the key.  Either you set the right one in your git config, or you add the e-mail that you were using to your GitHub online profile.  Now I show up as a contributor.  Hurray :)

**Comment by powroupi** [comment]
Great, i'd be happy to merge your changes. :smile:

**Comment by ptrthomas** [comment]
Sorry to keep this open for so long.  There is no issue with FBX export.

I'll raise another request for the changes.
