### ISSUE TITLE
Initial support for VMD export of model/camera

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#42]
Initial support for VMD export of model/camera
https://github.com/powroupi/blender_mmd_tools/commit/631eb87c1aaa56e5433d280524c69757fff51744

Hello @powroupi! Congratulations on all of your excellent efforts! Can you please clarify what you mean by "Initial support for VMD export of model/camera"? Should I announce to other people that MMD tools can now export VMD files? Or would that announcement be too soon?

**Comment by powroupi** [comment]
Hi @Hogarth-MMD, thank you for reporting this issue, and we can export "Basic" vmd file now. :smile: Currently, we can export bone animation, shape key animation, and camera animation, but lamp, self shadow, and other vmd specific animations are not supported yet, that's why i said "Initial support". There are still some issues need to be improved (not critical for now), and some notes may need to be documented. And yes, we can say we support VMD export now (hmm, maybe partially, ha ha). :smile: 

Notes (issues):
- Support f-curves only, drivers or NLA tracks are not supported. You may bake the animation to a new action if you want to export a final animation.
- The interpolations of bone rotation and camera rotation may not look right, since MMD use the same interpolation for all channels of rotation (x, y, z, w).
- In blender, select root empty object to export model animation (bone and shape key), select armature object to export bone animation only, select mesh object to export shape key animation only, select MMD camera object to export camera animation. And only active object's animation will be exported.
- Bone names are limited to 15 bytes (about 7 words of unicode character), there is no error message, just remember to keep bone names short.

**Comment by Hogarth-MMD** [comment]
Thanks for the information and all of your great work, @powroupi  !  I just shared this announcement to other people on my deviantart.com account:

http://hogarth-mmd.deviantart.com/journal/MMD-tools-can-now-export-VMD-files-644644129
