### ISSUE TITLE
Feature request: Auto translate material names

### ISSUE THREAD

**Issue by StrangerGithuber** [powroupi/blender_mmd_tools#47]
Hello
Can you add a feature which is translate automatically material names when I import in blender?

Because many MMD models has japanese material names.

**Comment by powroupi** [comment]
This is similar to #41 Morph translation.

Well, i don't think we can translate all japanese names, and it might not make sense to implement a translator in this addon. I think it is better to just use the property `name_e` (English Name) to set corresponding name in blender.

We may provide a tool to list the japanese names, and users use the translator they like to translate those names, and then this addon use them to fill english names, and you can choose to use japanese or english names to set corresponding name in blender ...things like that. I think this way is better. :smile:

**Comment by StrangerGithuber** [comment]
It sounds great. :)

**Comment by lordscales91** [comment]
@powroupi Actually, we already have a translation table [translations.py](https://github.com/powroupi/blender_mmd_tools/blob/6c125d9ea3944e1e82e5cc34f7aab2a041188e1d/mmd_tools/translations.py). Is it not being used? I think it's only used for bone names. We could extend it and use it to translate anything. But the manual translation is a better idea. It can be implemented as a new panel on mmd_utils tab. I will work on it.

**Update:**
It's a bit more complicated than I expected. My idea was to create a `TranslationPanel` and list there all translatable strings (bones, materials, morphs...) with an appropriate filter but... Actually, according to the docs you can only create lists of properties, not strings. Which means that in order to present all strings in a list we need to store them in properties, which implies having to sync them with the actual properties. Also this means that we will have duplicate data, which is not a good idea.

**Comment by stefnotch** [comment]
(I know just about nothing about how blender works, but) Aren't material names also properties?

Anyways, a translation panel sounds amazing!

**Comment by lordscales91** [comment]
@stefnotch 
> Aren't material names also properties?

Yes, they are, but each name is wrapped inside a `Material` object, and each material is wrapped inside a `Mesh` object, and an MMD model may have more than one mesh. Of course it's easy to list all them, there is a method in `MMDRoot` to do that, but it returns a list of material objects, not properties. An `UIList` which is the class that represents a list on the user interfaces can only handle properties, not raw strings nor any other type.

**Comment by powroupi** [comment]
@lordscales91 My original plan is to list japanese names in a text data block, users copy, translate, then paste english names to another text data block, and then we can use these 2 text data blocks as a reference (dictionary/mapping table) to update MMD english names. And the another thing is to update blender's names (JP/EN switch feature) which is a little complex to keep things work well.  :worried:

**Comment by lordscales91** [comment]
@powroupi Actually, I already thought about using text data blocks too. But I wanted to provide a better interface (an `UIList`). Sadly, given the limitations of Blender's UI system I think that's the only option.

**Comment by powroupi** [comment]
Translation function has been implemented, you might create your own csv dictionary or search from [this page](https://github.com/powroupi/blender_mmd_tools/wiki/Translations), so I'd like to close it for now, you can reopen it if you have new related questions. :)

**Comment by Hogarth-MMD** [comment]
https://github.com/powroupi/blender_mmd_tools/issues/128

mmd_tools helper add-on has a Reverse Japanese English operator.

Reverse Japanese and English names
Reverses the Japanese and English names of bones, shape keys and materials. The Japanese names become English names and the English names become Japanese names. If a Japanese name has no English name, it just stays the same. For someone who does not know Japanese, this operator can make it easier to edit an MMD model in Blender.
