### ISSUE TITLE
After i click "build"  import motion  Rigidbody is in a mess

### ISSUE THREAD

**Issue by qsqsaaw** [powroupi/blender_mmd_tools#49]
After i click "build"  import motion
 Rigidbody is in a mess,they are not following anything 
could you help me?
Sorry for my poor english
![rig](https://cloud.githubusercontent.com/assets/12880213/20801382/9f3d8cf0-b823-11e6-9292-0ad920998246.PNG)

**Comment by stefnotch** [comment]
Could you please post the download link for the model?

**Comment by nagadomi** [comment]
1. Rigidbody -> Clean
2. Move to 0 frame on timeline window (reset bone transformation)
3. Rididbody -> Build

Maybe this will fix it. I think this issue occurs when building a rigidbody during bone transformation.

**Comment by powroupi** [comment]
I'm not sure how you did that, but i know that happens in some case. If you build the model at the frame which is the start frame of rigid body cache, it should be fine. Otherwise, the rigid body cache sometimes mess the simulation. Currently, i'm not sure how to clean the cache through python :cry: , i assumed you understand the rigid body simulation and know how to adjust rigid body settings in blender. :)

p.s. [Properties] window -> [Scene] tab -> [Rigid Body Cache] panel (along with [Rigid Body World] panel)

**Comment by qsqsaaw** [comment]
That's wonderful.
I did what you said it works nice now.
Thanks a lot

**Comment by powroupi** [comment]
You are welcome. :smile: 
Well, i think this issue can be closed now. Thank you. :)
