### ISSUE TITLE
Some PMX files look deformed on import

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#50]
I've been testing mmd_tools on a wide variety of model files and it works great.  A few models (by the creator "SPS") have this issue - the hips are completely messed up, refer this image.

![mmd-tools-natu-bug](https://cloud.githubusercontent.com/assets/915480/20887936/b3fe316a-bb22-11e6-8d37-c3aebf85f30b.png)

Here's the link to the model download: https://bowlroll.net/file/74590
The password is the character's name in katakana: https://translate.google.com/#en/ja/natsu

Let me know if you need more info !

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

Well, this issue is fixed now, but i think this kind of bone issues would never be solved completely. And it sometimes lead to another issue when you fixed an issue. :(

But anyway, it's good to report issues if you found some, so that we have the chance to improve this addon. Thank you. :smile:

**Comment by ptrthomas** [comment]
@powroupi that sounds great.  Totally understand that we can't solve for everything.  I reported this because it looked like a very obvious problem.

From my side - now mmd_tools is amazingly stable and I've been importing many hundreds of models without issues.  I'll continue to report issues, even if they are not fixable I think it is good to add to  the discussion.  I really like following the discussions you have with the others even if I can't understand some of it !!

As always a video: https://www.youtube.com/watch?v=BeDZ9HBql30
