### ISSUE TITLE
Feature request: automatic generation of bones on export

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#53]
As an example of the kind of file I'm looking at, consider http://www.mediafire.com/file/odxzbzvwu0wukxt/77114_Crow.zip which was released CC-BY 3.0 by BillA on www.blendswap.com (redistributed, as allowed by license, so that you don't have to register).

The model is intended for use with blender and has some vertex groups and rigging.  When exporting the model to .pmx using mmd_tools (via Edit: Create Model, Edit: Attach Meshes, Model: Export), these vertex groups are lost.

My work-around for issues like this has been to use PMXE to create a model with bones using the same names as the vertex groups used by the .blend mesh, and to then import that model into the .blend file, join the .blend to the imported .pmx, and export it.  This preserves the vertex groups of the original .blend file.  (For anybody wanting to try this, note that mmd_tools chokes on .pmx files without any mesh data, so you'll need a perfunctory mesh, just a plane or something that you can delete afterwards.)  As an example of the kind of file I would create, check out http://www.mediafire.com/file/0fgvg0k5h0k3a24/crowbones1.pmx (note that one of the bones is misnamed, which happens frequently.)

Typically, I'll also reposition the imported bones as appropriate to the original file's armature, and set appropriate parents.

This process is slow and completely brainless, with a lot of room for transcription errors.  I think that makes it an ideal case for automation via mmd_tools.  I also believe that one of the popular uses of mmd_tools is importing models from foreign formats into MMD (often characters ripped from games), and so automation of this would probably be useful to more people than just me.

Automatic generation of bones in order to preserve vertex groups, even in the absence of any decisions about position or heirarchy, would be useful, even without taking the extra step of positioning or creating an appropriate heirarchy.  I can think of no cases where you wouldn't want vertex groups preserved into .pmx, and I think that any bone generation would make sense as a default, opt-out export option.

It may be the case that my workaround is a terrible, terrible way to do this, and some easier way to do it exists that I'm unaware of :)  In that case, I'd love to hear about it.

**Comment by lordscales91** [comment]
I think I see what do you want to achieve. You want to do the rigging in PMXE. Thus, you attached the mesh to a new MMD model and tried to export it right there. 

Of course it doesn't work because the PMX spec actually doesn't work with the concept of "vertex groups", when exporting, the vertex groups  are used to set the bone weights to the vertexes. You need to either do the rigging in Blender or import an existing armature and adjust it.

Ideally, if that model comes with an armature (which I suppose since it has defined vertex groups), We could implement a feature to attach the armature, or create one based on it in MMD style.

Sadly, it is really difficult to implement or even impossible unless we know the mapping of bone names.  We could however, add one bone per each vertex group and positionate it in the median point, which probably will be inaccurate but better than doing the rigging completely on your own. (And easier to implement). I will work on it when I have time. (unless other developer implements it before).

PD: For completeness, I must say that if bones doesn't comply with standard naming, motions will not load on it. Maybe it's just easier to rename the the vertex groups on the original model to comply with the standard and then attach it to an existing MMD armature (just take one from any model and then adjust it as you like. HELL! Why I haven't thought that before...).

**Comment by lordscales91** [comment]
PD2: Finally, for a reference to the standard bone naming you can check out [my tutorials on DA](http://fav.me/d9y5zbt)

**Comment by nathanvasil** [comment]
@lordscales91 "We could implement a feature to ... create one based on it in MMD style."

That is what I am requesting.

The issue is not where I want to do the rigging, but where I want to do the animation, which is in MMD.  In fact, I don't want to rig at all, because the models for which this is relevant are already rigged.  What I want is for the existing rigging to be exported to .pmx with less tedium or room for error than you get with manual positioning and naming.

The median point of each bone is probably not the ideal point for placement.  Bones in blender rotate around one end of the bone.  This point is the same point to which the cursor will snap (on being told to) when a bone is selected in pose mode..  That is the ideal placement for a .pmx bone created on the basis of a vertex group.  But even if bones were not positioned-- just clumped at the model's origin, for example-- the automatic generation of bones for .pmx exports would still be a good feature, as it would preserve Blender's vertex groups that would otherwise be lost on export.

Naming is not an issue, beyond the way that it establishes a correspondence between bones and vertex groups.  The model provided as an example is not a humanoid, and my goal is not to get it to use existing MMD motions, but rather to make it available for custom created animation inside of MMD.  Automatic translation from any of hundreds of possible naming conventions doesn't strike me as something worth doing-- close to impossible, really-- and it's not what I'm requesting.

**Comment by lordscales91** [comment]
Oh! A non-humanoid model, I could never guess it XD. It's not very frequent to see in the MMD community. So, you want to port a non-humanoid model with it's own armature to MMD. It's just as easy as create new MMD model (from Edit > Create Model). Delete the armature that it's created by default and attach the model's own armature to the MMD root. This will preserve the weighting, but all the bones will be movable by default. Also, There will not be display frames, unless you create them explicitly. I was about to show it you with a picture but... imgur seems down at the time of writing. Of course you can go bone by bone and tweaking out the MMD related properties. You will have troubles with the materials since they are procedural, created using nodes, you should find a way to convert them to standard textures.

**Comment by nathanvasil** [comment]
Thank you.  I've tested out your technique and it's working successfully.  I'll close this issue.
