### ISSUE TITLE
What's dummy bones for?

### ISSUE THREAD

**Issue by bomul0327** [powroupi/blender_mmd_tools#55]
I used TDA Append Miku 1.00 Model. After Importing, I found that the plugin make some dummy bones. Why are dummy bones created, and do deleting these bones affect animations or something else?

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

Yes, deleting those bones will affect animations. They are used for the function of 'Copy Rotation'/'Copy Location' in MMD style. You can apply or clean them (dummy bones and shadow bones) by hitting the 'Bone Constraints' buttons 'Apply'/'Clean'  of 'mmd_tools' panel. We need those bones because it won't look right by simply using 'Copy Rotation'/'Copy Location' constraints in blender unless the axes of source bone and target bone are well aligned.

I might be wrong or there might be a better solution, but so far, this solution works for most MMD models. :smile:
