### ISSUE TITLE
Can't export changed model currectly

### ISSUE THREAD

**Issue by qsqsaaw** [powroupi/blender_mmd_tools#58]
I import a pmx file change weight，then I export the model as pmx，I import it，The weight is same as origin。
Could you help me？  
import file
![000](https://cloud.githubusercontent.com/assets/12880213/25777833/0d997140-331d-11e7-9b9c-6733a6b7e01e.png)
make changes
![001](https://cloud.githubusercontent.com/assets/12880213/25777834/116078e6-331d-11e7-8061-e537b42044ea.png)
import again
![002](https://cloud.githubusercontent.com/assets/12880213/25777835/1674532a-331d-11e7-9621-0df520fb9783.png)

**Comment by nathanvasil** [comment]
Can you provide the model files?

Blender allows unnormalized weights-- weights that sum to less than or greater than 1.  It can be tricky to get these properly normalized prior to export, and I always double check prior to export (with the numeric display of weights on the property shelf, not by looking at the color).  You won't necessarily be able to see it on a weight view, because while one bone may be 1.0 (red) that doesn't mean that every other bone is 0.0 (blue).  IIRC, mmd_tools doesn't do much in the way of trying to be smart about weight normalization, and may not handle unnormalized weights the way you want, leading to what you're describing.

The actual model files would let me see if that's what the problem was.

**Comment by qsqsaaw** [comment]
OK

**Comment by qsqsaaw** [comment]
I rename it ，this is a pmx file

[why2.pdf](https://github.com/powroupi/blender_mmd_tools/files/981318/why2.pdf)

**Comment by qsqsaaw** [comment]
Following your advice ，I find out some weigt on "全ての親"
Now it‘s work well，
Thank you a lot

**Comment by nathanvasil** [comment]
I can't verify that was what was happening with only the initial (or final?) version of the model, but if you've got it working, it doesn't matter.

Please be aware of the effect that mmd_edge_scale and mmd_vertex_order vertex groups can have on normalization operations as well.  From the mmd_tools wiki:

"The default locking of mmd_edge_scale and mmd_vertex_order will not prevent them from factoring into the Normalize All tool (accessed from Weight Tools subsection of the Tools tab in Weight Painting mode) in Blender 2.77. If you need to normalize weights in Blender, you will need to delete these two vertex groups."
