### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#6]
Requesting @powroupi and @lordscales91 to join this discussion.

Really impressed to see the work you folks are doing, would like to help wherever I can.  Meanwhile I have a few questions below, and would really like to get your thoughts.
1. Is there a reason why the mix of rigid-bodies, joints and temporary-objects is so complex.  When importing, would it be possible to simplify things so that only hinge-joints and springs are used, and avoid the whole need to "clean" and "build".  I would really like to take a shot at this.
2. @lordscales91 - if I were to attempt an english translation of the documentation, would you help review it ?
3. Is exporting a motion / VMD something feasible ?  I can take a look at this.  I also want to build a library of NLA strips for common motions and poses.
4. Do you guys feel the pain of rendering animations.  I have been writing some python code to use AWS spot instances and do parallel renders etc.  Would you folks be interested in testing / contributing if I open-source this ?

**Comment by powroupi** [comment]
First of all, sorry for my english, please remind me if i wrote strange english, thank you very much. :)
1. Considering to export model, I can't find a way to improve this at the moment (maybe @sugiany can help). It should be easier to make a tool if you just want to setup the physics and play around in blender.
2. Sounds good.
3. I think it's possible to export bone and shape key motion, but that will be a little complex to deal with the animation curves, and the motion may not be identical because of the coordinate system transformation issue.
4. I might be interested in studying that, but i may not have much time to test or contribute it.

**Comment by ptrthomas** [comment]
@powroupi - thanks ! just curious, what is your main use-case for blender, are you just editing PMX models ?

**Comment by lordscales91** [comment]
Ok, here are my thoughts

1- I can't really give an opinion on this point because my knowledge of the Blender API is small. Also, my contributions to this addon were limited to just fixing some issues and the Morph Tools Panel, so I don't really know very much about the rest of the code.

2- I think that the current documentation (the README) is outdated, maybe it's better to create an updated English translation from scratch and then let @powroupi translate it to Japanese.

3- I agree with @powroupi on this point. Coordinate System transformations can be inaccurate.

4- I didn't knew about that concept, parallel rendering... You could render accurate high definition animations using high poly models in a small amount of time. Sadly, like powroupi I will not have time to test it. 

In fact, yesterday I should have been working on another project, a commercial one, but I was so immerse in coding this add-on that I spent the whole day on it. 
![he he](http://orig12.deviantart.net/987a/f/2013/343/f/c/hatsune_miku_14__teehee__by_jerikuto-d6wp0dv.gif)

That other project is for a business idea that I want to try, so eventually it will require more time. The reason why I decided to contribute to this addon is because I was so excited after knowing that this project was continuing. Also, my contribution to this addon was the first "real world" Python code that I wrote, so I have a special feeling for it.

From here I will talk a bit about my story, probably it's not the appropriate  place to do it, but if you are curious...

About my main use-case for Blender... I really don't have one ![ha ha](http://orig06.deviantart.net/4130/f/2013/343/a/9/hatsune_miku_04__laughs__by_jerikuto-d6tg9z2.gif) 
I had a plan of creating my own models for MMD, I watched modelling tutorials and I even purchased a new graphics card for that purpose. But then I realized that modelling a human body is very complex, even if it's not so much detailed like in an anime-like model. I wanted to create my own models because I was not comfortable with the [draconian](https://en.wiktionary.org/wiki/draconiano) rules that many MMD models have, so I wanted to create my own models and release them under the permissive Creative Commons licenses. Sadly I was not unable to accomplish it...

However luckily I recently met someone that is interested in modelling the models for me in exchange to some help with the process, which involves the use of this addon. That person is who reported to me the issues fixed in #3 

I will send to him some drafts of the original characters that I have in mind and he will model them for me ![Yay!](http://orig14.deviantart.net/df1a/f/2013/343/6/8/hatsune_miku_15__happy__by_jerikuto-d6wp0du.gif)

**Comment by ptrthomas** [comment]
Thanks @lordscales91 for the comments, and I really did find your motivations interesting.  I myself am interested in MMD and I totally agree with you about the draconian rules.  I was thinking the same myself, how can we help "free up" what the MMD world has become.  One crazy idea I had is to create a web-based PMX editor along with an online database of existing models and parts that you could re-mix.  Sadly, I don't think I have that much time on my hands >_<

But with Blender - this may be a realistic goal.  If we improve the documentation and the features, we can have more folks creating models this way.  And on Mac and Linux as well.  That reminds me - I have an idea for a "skirt physics" wizard in mmd_tools - which will create the bones, joints and rigid-bodies automatically - you just have to set the number of joints and the number of longitudinal segments.  What do you think, will this be useful ?

If you have heard of the [Rigify plugin](http://docs.unity3d.com/Manual/BlenderAndRigify.html) - I think a MMD <--> Rigify converter may open up a lot of possibilities.  Now, Unity3D is a whole different discussion ...

Here's my first attempt at creating an MMD video using Blender: https://www.youtube.com/watch?v=sElibfBCnXw

**Comment by powroupi** [comment]
> thanks ! just curious, what is your main use-case for blender, are you just editing PMX models ?

@ptrthomas Because i feel more confortable to use blender than pmx/pmd editor, this addon becomes my first choice, and i want to improve it as possible. I even like to contribute this addon more than editing/playing mmd. :)

**"skirt physics" wizard** <-- Possible! Once we can create the skirt bones, we should be able to add rigidbodies and joints quickly.

And nice video :+1: 

> 2- I think that the current documentation (the README) is outdated, maybe it's better to create an updated English translation from scratch and then let @powroupi translate it to Japanese.

@lordscales91 Unfortunately i can't do that, we need to invite other people/japanese to translate. >_<

And good to know your story. :)

**Comment by ptrthomas** [comment]
> And nice video :+1:

Thanks @powroupi  :)  And I shall start looking into creating a skirt physics wizard.  At least that way I will understand the mmd_tools rigid body system a little better - and possibly find ways to simplify it later.

**Comment by lordscales91** [comment]
> Because i feel more confortable to use blender than pmx/pmd editor, this addon becomes my first choice, and i want to improve it as possible. I even like to contribute this addon more than editing/playing mmd. :)

@powroupi  I feel the same, PMX editor is too simple, and many people have trouble using it because of the Japanese locale. And sorry, I assumed somehow that you speak Japanese, maybe was the username. 

@ptrthomas I don't see too much documentation about Rigify, but from what I saw it seem that it just generates an armature. While it is something that must be done in order to animate a character, there is another more important step which is the 'weight paint'. On the Unity tutorial you linked they call it skinning, and they suggest to use the Blender's automatic weight, which is a good idea but... I don't see the point of an interaction between MMD Tools and Rigify. If you want an armature. You can just create one (or import an existing one from a MMD model) once and use it as a base for all your models, of course you will need to adjust the armature to each character, as well the weight paint.

About Unity3D, I actually had the idea of creating an open.source multi-platform MMD, and I thought about the possibility of make it Unity-powered. But as you said, that would require a lot of time, which I don't have. I think it's a better approach to improve this add-on so non-Windows users could use Blender as a MMD replacement. However, the good thing about MMD is that it is very simple. Blender is too much powerful and the interface may scare new users. That's why I wanted to create a new MMD, but the demand is very low and I don't have time.

**Comment by powroupi** [comment]
By the way, here is the URL of blender api documents that i frequently used:

For current/latest version:
[https://www.blender.org/api/blender_python_api_current/](https://www.blender.org/api/blender_python_api_current/)

For old versions:
[https://www.blender.org/api/](https://www.blender.org/api/)

**Comment by ptrthomas** [comment]
@lordscales91 my thinking was there should be a lot of Rigify models out there and that it might be cool to "retarget" VMD motion data to those.  Besides the "simple" factor that you pointed out, MMD has this great thing going for it - which is the existence of a huge pool of high-quality motion-data, and designed to work near-perfectly on any PMD/PMX model !  

That said, are you folks aware of the [MMD to Unity converter](https://laboratoriesx86.wordpress.com/2015/04/26/tutorial-mmd-4-unity/) ? I found it does a brilliant job of converting PMX/VMD into a ready to use Unity3D scene.

**Comment by ptrthomas** [comment]
thanks for the great discussion ! @powroupi you can close this issue.
