### ISSUE TITLE
What are shadow bones and dummy bones?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#63]
In an MMD model, there are no shadow bones and no dummy bones. But when an MMD model is imported by mmd_tools, shadow bones and dummy bones are added to the MMD model. Can someone please explain to me: What are these shadow bones and dummy bones and what function do they have? I am completely clueless and ignorant about this.

I was starting to think a little about how bone pose morphs can be added to MMD_tools, and this question entered into my mind.

**Comment by powroupi** [comment]
About shadow bones and dummy bones, you might reference #8, #55. :smile: 

>I was starting to think a little about how bone pose morphs can be added to MMD_tools, and this question entered into my mind.

Do you mean previewing with a animation (just like UV morph)? We already can add/remove/modify bone morph data with Morph Tools.  :open_mouth:

**Comment by Hogarth-MMD** [comment]
Yes I mean posing and animating with bone pose morphs in Blender.

**Comment by Hogarth-MMD** [comment]
@powroupi I am not understanding what you mean when you say "well aligned".

"We need those bones because it won't look right by simply using 'Copy Rotation'/'Copy Location' constraints in blender unless the axes of source bone and target bone are well aligned."

"The bones created by mmd_tools.core.bone.FnBone.apply_additional_transformation are for fixing bone roll/direction issue, which may not be necessary if the source bone and the target bone are well aligned."

**Comment by Hogarth-MMD** [comment]
So these bones are hidden on a hidden bone layer. This is helpful information, thank you.

**Comment by powroupi** [comment]
"well aligned" means the X/Y/Z axis direction of source bone and target bone are (nearly) the same. You may need to enable "Axes" in armature's Display panel to show bone axes (in Pose mode or Edit mode).
If the axes of source bone are (1, 0, 0), (0, 1, 0), (0, 0, 1), then the axes of target bone need to be (nearly) the same, otherwise, dummy and shadow bones will be created for correct result of Move/Rotate append. (I'm not good at explaining things, sorry) :sweat_smile:
