### ISSUE TITLE
Exporting uneditable PMXs

### ISSUE THREAD

**Issue by nathanvasil** [powroupi/blender_mmd_tools#69]
Another situation where mmd_tools is exporting a MMD readable model but not a PMXE readable model (corrupted header?  I don't know.)  Using PMXE from https://eoscustom3d.deviantart.com/art/English-Pmx-Editor-v1-1-542100208 .  Bad .blend + .pmx are at http://www.mediafire.com/file/v31u19hsg3hexcv/badexports.zip .  Apologies for the size of the file.

As to how I've  created such a mess of a file: I have curve objects that I fit to my current version of a model.  When I decide that some part isn't good enough, I import my current model, often just for placement and visualization, and adjust the curve, then create a mesh object from it.  In these case, I don't need the entire model, my goal is really just to get a copy of my adjusted mesh out of Blender, which I can integrate into my model relatively worry free in PMXE.  In the files provided, there are a few adjusted materials off to the side of the main model; those are all I care about getting out of Blender.  After a bit of work, these files can accumulate several different MMD models; well, copies of the same model, really.

I'm sure that my style isn't the best for doing this, and any recommendations for ways I should be doing things differently are welcome.  For example, is there some good, simple way to remove a MMD model from a scene?  Deleting it from the outliner leaves a lot of debris.  Eventually I managed to get my meshes exported from this file, but I'm not sure exactly how :)

However, I also think that mmd_tools probably shouldn't be exporting uneditable .pmx files.

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

I'm sorry I'm a little busy. You might try to re-import corrupted pmx, change import option to import specific parts only, then re-export pmx to identify which part causes issues. (I guess it's possibly mesh part issue) And there might be a workaround before I fix the issue. :)

1. Import only `Armature`(click import option `Armature`), export `arm.pmx`, if uneditable, armature part issue, otherwise, try step 2.

2. Import only `Armature+Physics`(click import option `Physics`), export `arm_phy.pmx`, if uneditable, physics part issue, otherwise, try step 3.

3. Import only `Mesh`(click import option `Mesh`), export `mesh.pmx`, if uneditable, mesh part issue, otherwise, try step 4.

   - if mesh part issue, try import only `Mesh`, then remove all materials, export `mesh_pure.pmx`, if uneditable, mesh issue, otherwise material part issue.

   - if material part issue, try import only `Mesh`, then remove all textures, export `mesh_no_tex.pmx`, if uneditable, texture issue, otherwise material issue.

        - if texture issue, try import only `Mesh`, then remove all base or toon or sphere textures to see which texture type issue.

4. Import only `Mesh+Armature+Morphs`(click import option `Morphs`), export `mesh_arm_morph.pmx`, if uneditable, morph part issue, otherwise, display item part issue.

**Comment by nathanvasil** [comment]
Thanks, understood that you're busy, the work that you've done with mmd_tools is fantastic.

Like I said, I worked around it in this particular case, even if I don't know exactly how.  Limited reimport is a great idea that I'll try next time this happens (in these situations, I'm usually only looking for mesh data).

**Comment by powroupi** [comment]
Sorry for my late reply, thank you for liking this tool, and I think this issue should be fixed now. :smile: It is the issue of "Copy textures" which exports duplicated texture path in some cases, and PMDE/PMXE cannot accept that. :)

>For example, is there some good, simple way to remove a MMD model from a scene? Deleting it from the outliner leaves a lot of debris.

In outliner, RMB click on MMD Root object (shows [Outliner Object Operation] menu), hit **[Delete Hierarchy]**.

**Comment by nathanvasil** [comment]
Thank you very much!

I thought I'd tried deleting hierarchy in the past with poor results.  But that was an earlier version of mmd tools and an earlier version of Blender.  Or maybe it was me.  Either way, working great now.  Thank you.
