### ISSUE TITLE
Suggestion: Bones naming convention dropdown: Default, Unity

### ISSUE THREAD

**Issue by JakubNei** [powroupi/blender_mmd_tools#78]
If I import with default translations.py and then export to FBX into Unity, then Unity has hard time automatically finding the bones. If I change translations.py in the following way, Unity is more likely to find correct bones by name. Still some manual work is needed based on the armature architecture, but it's easier if Unity finds most of the bones on it's own.

UpperBody -> Chest
LowerBody -> Spine
Wrist -> Hand
Ankle -> Foot
Waist -> Hips
Arm -> UpperArm
Elbow -> LowerArm
Leg -> UpperLeg
Knee -> LowerLeg

I suggest a new dropdown:
Bones naming convention: Default, Unity

**Comment by powroupi** [comment]
Thanks for your suggestion. :smile: 

In short term, you might replace corresponding names of [jp_to_en_tuples in translations.py](https://github.com/powroupi/blender_mmd_tools/blob/83f1a762ceb8dd32be76f1cee04d3f46b8387283/mmd_tools/translations.py#L27) to fit your requirement.

In long term, I'm planning to use custom csv dictionary because this way can be easier to fit different requirements. :smile:  (you might be interested: issue #61)

**Comment by JakubNei** [comment]
Alright, thanks.

**Comment by Hogarth-MMD** [comment]
Did you download this? It includes a bones-renaming script (renaming DAZ/Poser bones to MMD Japanese bones) which you can re-edit yourself fairly easily to the rename bones to a different armature type, such as Unity. 

https://github.com/Hogarth-MMD/mmd_tools_translation

https://github.com/Hogarth-MMD/mmd_tools_translation/archive/master.zip

**Comment by JakubNei** [comment]
No, I've directly edited translations.py
But looking at it, I might reimport with your dictionary.
Why isn't your dictionary part of these tools ? It would make sense to have it here instead.

**Comment by Hogarth-MMD** [comment]
It's very recent and WIP. Maybe later @powroupi will add it into mmd_tools.

**Comment by powroupi** [comment]
Yeah, maybe I'll add it into mmd_tools if @Hogarth-MMD agree that when the dictionary is more completed.  :yum:

**Comment by Hogarth-MMD** [comment]
Hello @powroupi!
Today, I just posted a journal entry about the new mmd_tools translation feature:
https://hogarth-mmd.deviantart.com/journal/mmd-tools-new-translation-feature-710613223

I do think that my translations.csv should be added to mmd_tools at some time in the future. But please do not do this immediately or without giving me some warning beforehand, because when you add my translations.csv into mmd_tools I will need to re-write the instructions which I have written for the mmd_tools translation feature.

**Comment by powroupi** [comment]
>But please do not do this immediately or without giving me some warning beforehand,

Okay, or maybe you can give me some messages or make a pull request when the dictionary is good enough, then I add it. :smile:

**Comment by powroupi** [comment]
Hello, I've made some changes for custom csv dictionaries, you might try it. :smile: 

@Hogarth-MMD, you may need to update your tutorial, major changes:
   - Change `Translate` button label to `Translation`.
   - Now file name does not have to be `translations.csv`, and can be located to custom folder. You can change custom folder via mmd_tools addon preferences.
   - The dropdown list will list all *.csv files in the custom folder (sub folders are not included) and *.csv blender texts.
