### ISSUE TITLE
bone morphs slider controls?

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#82]
How are you doing @powroupi ? :smile:  I hope that you are doing well.

Example bone morph location and rotation data:

>>> bpy.context.active_object.mmd_root.bone_morphs[0].data[0].location
Vector((0.0, 0.0, 0.0))

>>> bpy.context.active_object.mmd_root.bone_morphs[0].data[0].rotation
Quaternion((0.9940563440322876, 0.1088668555021286, -2.4513144335561177e-13, 9.518605459390983e-09))

I have been trying to make a Blender python script which implements morph control sliders for bone morphs. However there is an issue with how the X,Y or Z axis of a bone is defined. With Blender drivers on pose bones, it seems that X,Y, or Z are defined as the local axis of a bone. And also the world Y or Z axis is defined differently in MMD and Blender. So please tell me what is the correct technique to translate the bone morph data into data which will be correctly used by Blender drivers? :smile:

**Comment by nathanvasil** [comment]
Hi Hogarth.  I can't solve your problem.  However, MMD interprets bone morphs according to a bone's local axes, not the world's axes.  For example, if you create a bone morph rotating a knee in the X axis, it will rotate in the correct direction regardless of how the hip is twisted or how the center is twisted.  On a recent model, I'm using bone morphs like this to hyperextend the leg, which wouldn't work if it was using the world coordinate system to apply the bone morphs-- if the model's center was rotated 90 degrees in MMD's Y axis, the leg would rotate sideways at the knee, rather than forwards to hyperextend the leg.

There may be something else going on.  For example, MMD bone morphs do not respect the "axis limit" or "local axis" settings.  Blender may be respecting this (MMD really ought to.)  In addition, Blender models typically have axes similar to MMD's "local axis" for all bones, whereas few MMD models even use this property.

BTW, you're never ever going to be able to get any useful info out of looking at raw quaternions.  To figure out what's going on, probably even to change coordinate systems, you're probably going to have to convert to Euler angles or something and then back to quaternions.  I imagine Blender has good functions for doing so.

**Comment by Hogarth-MMD** [comment]
Hi @nathanvasil  Thanks! If you want to help out with getting advanced morphs slider controls into Blender, it could be helpful to have an ideally simple .pmx test model, like a cube which has 1 or 2 of every type of morph, for example.

**Comment by Hogarth-MMD** [comment]
Hi @nathanvasil (or whoever), are you able to tell me which (x,y or z) axis of a pmx bone is its twist axis?

**Comment by nathanvasil** [comment]
Sure, I can do that quickly.  Tomorrow AM.  (Edit: make the model, I mean.)

So I think I can explain how to do what you want to do, but some of the details are dependent on the way that Blender (OpenGL) makes some arbitrary decisions, similar to the way that it uses Z as the up vector.  Also, I'm very, very far from expert on any of this, I still have to make a lot of trial-and-error mistakes when I do this kind of stuff, so please don't take anything I'm about to say as gospel.

Okay, let's say you have a bone's local coordinate transformation (in the form of a 4x4 matrix) and you have a transformation you'd like to apply to that bone (in the form of a quaternion) but that transformation exists in the MMD coordinate system.

So the first thing you do is you transform the bone from Blender's coordinate system to MMD's coordinate system.  First, let's rotate it -90 degrees in the X axis so that Blender's Z axis agrees with MMD's Z axis.  Here's my code to create a 4x4 rotation matrix:

float4x4 rotate (float3 rot) {
//first in x, then y, then z
//radians

	float sinX = sin(rot.x);
	float sinY = sin(rot.y);
	float sinZ = sin(rot.z);
	float cosX = cos(rot.x);
	float cosY = cos(rot.y);
	float cosZ = cos(rot.z);
	
	float4x4 rotMatrix = {
		{cosY*cosZ, (cosZ*sinX*sinY)-(cosX*sinZ), (cosX*cosZ*sinY)+(sinX*sinZ), 0},
		{cosY*sinZ, (cosX*cosZ)+(sinX*sinY*sinZ), (cosX*sinY*sinZ)-(cosZ*sinX), 0},
		{-sinY, cosY*sinX, cosX*cosY, 0},
		{0, 0, 0, 1},
	};
	
	return rotMatrix;
}

Multiply the bone's local axis by that matrix to rotate it.

Okay, now Y is pointing in the right direction, but Z is pointing in when it should be pointing away.  So let's scale Z by -1.  Start with an identity matrix, which is {{1000}{0100}{0010}{0001}}.  The Z scalar is in the third row and the third column.  Multiply that by -1, so that it becomes -1.  Multiply the bone's local axis by this scaling matrix, and the bone is now transformed into MMD coordinate space.

Now we can multiply in the quaternion that's coded in the MMD coordinate space.  But we're not quite done-- we have to transform the bone back into Blender coordinates.  That's not so hard, it's just reversing the operations.  First, we'll multiply its matrix by our -1 Z scaling matrix (it is its own inverse matrix).  Then, we'll rotate our matrix 90 degrees in the X axis-- the inverse of our rotation matrix.  There's a trick to make that, but you can just use that same code I put above.

Note that we don't even need the bone's local axis to create this transformation.  Those transformations multiplied together form their own transformation that we can keep and apply to any particular local axis.  Since we've multiplied in a quaternion, it's in the form of a quaternion (float4) rather than a matrix.  We can store that float4 as a transformation to apply to any matrix representing the transformation of the bone.

I said that a lot of this stuff depends on Blender and OpenGL conventions.  I'm used to HLSL, which does a lot of stuff backwards from OpenGL.  For example, where HLSL expects a column, OGL expects a row (so that rotation code probably needs to be transposed for OpenGL.)  Also, OGL may expect matrix multiplication, which is not commutative, to be performed in the opposite order of HLSL.  There may be other details of which I'm unaware-- I'm offering this more as a way to think about the problem, but the details still need to be ironed out.

**Comment by nathanvasil** [comment]
>Hi @nathanvasil (or whoever), are you able to tell me which (x,y or z) axis of a pmx bone is its twist axis?

Oh, we're typing at the same time.

MMD bones don't have length, so there is no distinguishing roll from yaw or pitch.  There is only rotation.  If a bone seems to be pointing in the -Z, like a thumb, its roll is in the Z axis.  If it seems to be pointing in the +Y, like a neck, its roll is in the Y axis.  If it has no clear axis, like most arms, it has no clear roll axis-- there is no way to rotate a typical MMD arm in a single local axis and give it only roll.

**Comment by Hogarth-MMD** [comment]
Thanks, @nathanvasil , I just tested a pmx model in MMD and a bone's twist axis can be either x, y or z. It seems pretty weird and complicated. In Blender, a bone's Y axis is its twist axis.

**Comment by Hogarth-MMD** [comment]
Thanks @nathanvasil ,. Probably mmd_tools has whatever functions it needs to deal with bone axis differences between MMD and Blender, so I'll wait for @powroupi  to reply to me about that.

**Comment by nathanvasil** [comment]
http://www.mediafire.com/file/joopbkb8wz358pu/morphtestcube.zip has several morphs for testing purposes.

**Comment by powroupi** [comment]
@Hogarth-MMD 
>it seems that X,Y, or Z are defined as the local axis of a bone. And also the world Y or Z axis is defined differently in MMD and Blender

Yes, the X,Y,Z of bone morph data are defined as the local axis of a bone, and Blender's world XYZ = MMD's world XZY. In Blender, you can use bone morph data directly like `pose_bone.location = bone_morph_data.location` or `pose_bone.rotation_quaternion = bone_morph_data.rotation`. And as @nathanvasil said, MMD does not respect bone local axis but Blender does respect this. :)

If you are curious about how bone morphs are converted,you may take a look [pmx.importer](https://github.com/powroupi/blender_mmd_tools/blob/3e19c942a0d9d2b535291ba97077800023eefea9/mmd_tools/core/pmx/importer.py#L681-L683) and [pmx.exporter](https://github.com/powroupi/blender_mmd_tools/blob/3e19c942a0d9d2b535291ba97077800023eefea9/mmd_tools/core/pmx/exporter.py#L686-L690). :smile:

**Comment by Hogarth-MMD** [comment]
Thanks for your help @nathanvasil @powroupi  . Hopefully soon I'll have the first version of a bone morphs slider controls script to share.

**Comment by Hogarth-MMD** [comment]
An example driver scripted expression for a bone's W quaternion value:
```
1.000+0.7071068286895752*ZRotBottomBone+0.5*XZRotBottomBone
```
This example expression is buggy and incorrect but I am not seeing how to correct it. This buggy expression is incorrectly adding 1.0 to the W value of the morph sliders. I cannot change it to multiplying by 1.0 because, in that case, the bone will have an incorrect W value of 0 when the morph sliders are set to zero. For the same reason, I cannot subtract 1.0 from this expression (because, in that case, the bone will have an incorrect W value of 0 when the morph sliders are set to zero). How do I correct this?

In its zero rotation pose, a quaternion bone has a W value of 1.0. 
This seems to be a simple problem, but my script-writing is completely befuddled by this seemingly simple problem. Arghhh!

**Comment by Hogarth-MMD** [comment]
Okay, no problem. Apparently I just needed to add a -1 at the correct place in my script and now my script now seems to be working fine. LOL.

**Comment by Hogarth-MMD** [comment]
Blender has a bug which prevents us from having Japanese characters in names for the morph slider controls. Seemingly this bug happens because a Blender driver scripted expression is being parsed as bytes, while the driver variable is being parsed as characters. In some (or all?) Japanese characters, one character may be 2 bytes, but because of this Blender bug, these characters in driver scripted expressions are not being correctly parsed.
The result is this error message in the Blender system console:

Error in Driver: The following Python expression failed:
   ...
NameError: name ... is not defined

Because of this bug, the morph names must come from the English names of morphs and if the English name of a morph has any Japanese characters in it, you need to delete these characters using the mmd_tools morph tools panel (or delete them in pmx editor or whatever). (I am using Blender 2.7.8,)

This is the only serious problem that I am seeing and otherwise, my script is now working and creating the bone morph slider controls.

**Comment by Hogarth-MMD** [comment]
In earlier versions of Blender, a driver scripted expression was limited to a maximum of 25 characters. In a recent version of Blender, this bug was fixed, but it may be a problem for someone who is using an earlier version of Blender.

**Comment by Hogarth-MMD** [comment]
A few useful pieces of python code to use with driver controls:
Enable all drivers:
```
def enable_all_drivers_active_object():
	if bpy.context.active_object.animation_data is not None:
		for d in bpy.context.active_object.animation_data.drivers:
			d.mute = False
```
Disable all drivers:
```
def disable_all_drivers_active_object():
	if bpy.context.active_object.animation_data is not None:
		for d in bpy.context.active_object.animation_data.drivers:
			d.mute = True
```
Reset all custom properties to zero:
```
for cp in bpy.context.active_object.data.keys():
	if cp != "_RNA_UI":
		bpy.context.active_object.data[cp] = 0.0
```

**Comment by Hogarth-MMD** [comment]
Thank you @nathanvasil. Your test model was essential to alerting me to the W quaternion issue and in helping me to correct it.

**Comment by Hogarth-MMD** [comment]
Okay, that annoying Blender bug with Japanese characters wasted some time for me, but now I have successfully implemented a workaround and now we can have Japanese characters in the names of  morph slider controls. I was thinking that the driver variable name needs to be the same as the name of the morph slider control, but that idea was not correct.

**Comment by Hogarth-MMD** [comment]
Poll question:
1) Do you (anyone) want me to upload my script immediately?
or 
2) Are you satisfied to patiently wait until after I have converted it from a standalone script into an add-on?

**Comment by nathanvasil** [comment]
>Blender's world XYZ = MMD's world XZY.

You have to be careful with this, you can't always just interchange Y for Z.  Euler angles depend on the order in which they're evaluated, which is usually XYZ.  Rotating  30 degrees in Y then 45 degrees in Z isn't the same thing as rotating 45 degrees in Z then 30 degrees in Y.  (But I'm not sure what happens when you swizzle a quaternion.  Might be something worth experimenting with.)

**Comment by Hogarth-MMD** [comment]
Hi @nathanvasil  You can find very lucid explanations of Euler and Quaternion rotation interpolations in these 2 videos from the Humane Rigging DVD:

Axis Angle & Euler Rotation
https://www.youtube.com/watch?v=syQnn_xuB8U

Quaternion Rotation
https://www.youtube.com/watch?v=4mXL751ko0w

Order of rotation is not an issue for quaternions. Quaternion rotation interpolation happens along geodesics. The numbers used in quaternions are trigonometric ratios of an angle/2. W represents the unrotated angle. The X, Y and Z values = 1.0 represent 180 degree rotations around X,Y,Z axis. A quaternion  angle is defined as a mixing of these 4 angles, analogous to an RGB mixing of colors.

**Comment by powroupi** [comment]
There might be some issues on Blender drivers. If you add drivers on location/rotation/scale of a pose bone, the bone will not be controllable by user, and the motion/pose may not work on that bone.  :worried:

**Comment by Hogarth-MMD** [comment]
I haven't noticed any problem using drivers with pose bones.

**Comment by Hogarth-MMD** [comment]
Or do you mean that in Blender an object cannot be animated by a driver and by a key frame animation both at the same time? Is that what you mean,  @powroupi ?

**Comment by powroupi** [comment]
I mean the bone will not be able to move if you add drivers on a pose bone's location properties, (the bone will not be able to rotate if you add drivers on a pose bone's rotation properties), the drivers will work but user will not be able to move or rotate that bone. :(

>Or do you mean that in Blender an object cannot be animated by a driver and by a key frame animation both at the same time?

Yeah, I think so. :)

But I'm not sure how you add drivers for bone morphs slider, there might be some workarounds. :thinking:

**Comment by Hogarth-MMD** [comment]
Hello @powroupi !

In one of my posts above, I posted the python code to disable or enable all drivers. This allows the user to toggle back and forth between control by user and control by drivers. 
 
In some of the bone pose morphs that I have seen in MMD models, the bone pose morphs are being used to animate facial bones. The facial bone morphs have the exact same names as the standard MMD vertex facial morphs, so there is no issue of a conflict with VMD animations in that case.

In the models by Pluto, the bone pose morphs are being used to fine tune breasts animation or to hide or reveal or adjust a piece of clothing. The bones which are being controlled by bone morphs in models by Pluto are not normally animated by a VMD animation, so there is also no potential conflict with VMD animations in that case. 

After the advanced morphs (bone, uv, material, group) slider controls have been added to mmd_tools, we will need to have a new feature to import and export VMD animations of the advanced morphs. Presumably it will all take some time. This is life, almost nothing happens instantly, but progress is being made. :smile:

**Comment by Hogarth-MMD** [comment]
Okay, here is the download for my standalone python script for creating bone morph slider controls:
https://sta.sh/0o5w5boibt7

**Comment by Hogarth-MMD** [comment]
1. Import a .pmx model into Blender using the mmd_tools add-on (powroupi fork).
This model must have one or more bone morphs, all of which must have an English name. Future versions of this script may use the Japanese name of a bone morph, but this has not yet been implemented.

2. Open this file in the Blender text editor:
mmd_tools_bone_pose_morphs_1.0.py
Click on the Run Script button to run the script.
(It does not matter which object in the scene is the active object.)

3. Running this script creates bone morph slider controls which you can find by first selecting the armature object to make it the active object. The bone morph slider controls will be located under Custom Properties under the Data tab (stick man icon) in Blender's Properties Window. The slider controls should work in either Object mode or Pose mode.

**Comment by Hogarth-MMD** [comment]
Okay, I have made the GUI elements. Now I just need to add some code for allowing Japanese names to be used on bone morphs slider controls. (With my luck, my computer will probably die one minute before I can upload this new add-on. We will see what happens. :smile: )

**Comment by powroupi** [comment]
I'd like to close this issue since the features (bone/UV/group morph slider controls) have been implemented. :)
