### ISSUE TITLE
MMD tools only shows up if you remove ALL other addons

### ISSUE THREAD

**Issue by xavierneko** [powroupi/blender_mmd_tools#89]
Spent about an hour trying to add this, the only way I have been able to add it is if I removed every single addon in the addon folder and added this tool all by itself, if all the other addons are in the directory with this tool, it refuses to show up in the add-ons directory in blender

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 

To install `mmd_tools` to Blender:
1. Copy the **mmd_tools** folder to [Blender folder]\[Blender version]\scripts\addons, (as a result, blender-2.79-windows64\2.79\scripts\addons\mmd_tools\ for example)
2. Enable `mmd_tools` in Blender from the Add-ons tab of the User Preferences dialog. Do not use [Install from File] button to install `mmd_tools`, it may not work as expected.

If this issue still happens, you might attach some screenshots or paste the console messages so that I can debug it more easily. Thank you. :)

**Comment by Darkblader24** [comment]
@powroupi What do you think about making mmd_tools installable with the Blender installer?
I see a lot of new people struggling with installing and updating mmd_tools because they try to install it as a zip. 
Making that possible would make installing a lot easier. Currently I have to describe two different ways of installing plugins
Btw thank you so much for continuing mmd_tools! ❤

**Comment by powroupi** [comment]
>What do you think about making mmd_tools installable with the Blender installer?

I have no confidence to do that because it might require to change the directory structure of this repository. :worried:  Maybe easier way is to simply provide a pre-zipped file `mmd_tools.zip` for download. :)

But I've never had the issue like @xavierneko said. :confused:

**Comment by xavierneko** [comment]
For some reason, now it is finally working, its weird, I've reinstalled Blender multiple  times with different versions and now it just started to want to work, thank you
