### ISSUE TITLE
physics visibility

### ISSUE THREAD

**Issue by Hogarth-MMD** [powroupi/blender_mmd_tools#97]
In MMD, PMD editor, PMX editor, the visibility of physics can be turned on and off. I recommend that this feature should be added into mmd_tools. The purpose of this feature would be editing of physics in Blender.

**Comment by nathanvasil** [comment]
You can display rigid bodies (and/or joints) using the MMD Display subsection of the properties shelf.  Just check 'Rigidbody'.

**Comment by Hogarth-MMD** [comment]
Thank you for this helpful information. This easy-to-overlook feature is located at the bottom right side of the 3D view window. What is a "temporary object"?

**Comment by powroupi** [comment]
>What is a "temporary object"?

Temporary objects are empty type objects which are set up for bone tracking and non collision object pairs. Currently, it only shows the objects for bone tracking when you check "temporary object".

Because Blender does not have MMD-like collision group/mask properties, we create lots of empty objects for disabling collisions between rigid body objects.

**Comment by Hogarth-MMD** [comment]
Thank you @powroupi. Wow, so much patience and perseverance and cleverness has been needed to program mmd_tools!
